// Contract tests for the shared beat IMPLEMENT runner. Executes the workflow with mocked
// primitives so the dispatch policy is tested without spawning implementation agents.
// Run: bun test tests/beat-implement-runner.test.mjs
import { createHash } from 'node:crypto'
import { existsSync, lstatSync, mkdtempSync, mkdirSync, readFileSync, rmSync, symlinkSync, utimesSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { createServer } from 'node:net'
import { captureApprovalBundle } from '../workflows/lib/approval-bundle.ts'
import { captureGitObservation } from '../workflows/lib/git-observation.ts'
import { fingerprint } from '../workflows/lib/task-contract.ts'
import { runWorkflowModule } from './helpers/workflow-module.mjs'

const ROOT = new URL('..', import.meta.url).pathname
let PASS = 0, FAIL = 0
const ok = (name, condition, extra = '') => {
  if (condition) PASS++
  else { FAIL++; console.log(`FAIL  ${name}${extra ? ` — ${extra}` : ''}`) }
}

// THE RACE-INJECTION SEAM THAT USED TO LIVE HERE IS GONE, AND WAS NOT RE-POINTED.
//
// It rewrote this script's source with `.replace('readFileSync(fd)', 'snapshotReadFile(fd, full)')`
// and `.replace('lstatSync(full)', 'snapshotLstat(full)')` to swap in snapshot doubles. Both call
// sites left beat-implement.js: the read moved into `readArtifactSnapshot` in
// workflows/lib/approved-artifact.ts, and `lstatSync(full)` no longer exists anywhere in the repo.
// `String.prototype.replace` no-ops silently on an absent literal, so the doubles were never
// installed, `trace.snapshotReads` was permanently empty, and `freezeSnapshotMetadata` froze
// nothing — both checks below passed without exercising anything.
//
// Re-pointing was not available and would have been the wrong instinct anyway: string rewriting is
// what rotted. The runner now touches no filesystem primitive at all (it imports none from
// `node:fs`), so there is nothing here left to double. The two properties the seam supported are
// re-derived below against the shipped design — one structurally, one with a real fixture — and the
// TOCTOU window itself is asserted where the code and its dependency-injection seam actually live,
// through `ArtifactReadOptions.beforeOpen`/`afterOpen` in tests/approved-artifact-contract.test.ts
// ("rejects a receipt substituted after the receipt descriptor is opened" and its plan-bytes twin).
const source = readFileSync(ROOT + 'workflows/beat-implement.js', 'utf8')
const plan = '# Approved plan\n'
const hash = createHash('sha256').update(plan).digest('hex')
const planFile = 'jazzy-leaping-scroll.md'
const reset = { planFile, planHash: hash }

function projectFor(options = {}) {
  const project = mkdtempSync(join(tmpdir(), 'beat-implement-'))
  const planning = join(project, '.planning')
  const state = join(planning, '.state')
  const approvedPlan = options.plan || plan
  const approvedHash = createHash('sha256').update(approvedPlan).digest('hex')
  mkdirSync(state, { recursive: true })
  const selectedPlanFile = options.planFile || planFile
  writeFileSync(join(planning, selectedPlanFile), approvedPlan)
  writeFileSync(join(state, 'review.json'), JSON.stringify({
    workflow: options.workflow || 'ds',
    plan_file: options.statePlanFile || selectedPlanFile,
    plan_hash: options.reviewHash || approvedHash,
    approved_session_id: options.approvedSession || 's-123',
    approved_at: options.approvedAt || '2026-01-01T00:00:00.000Z',
    status: options.reviewStatus || 'APPROVED',
    reviewer_session_id: options.reviewStatus === 'PENDING' ? '' : (options.reviewerSession || 'reviewer-456'),
    reviewed_at: options.reviewStatus === 'PENDING' ? '' : (options.reviewedAt || '2026-01-01T00:00:01.000Z'),
    ...(options.metaExtra || {}),
  }))
  Bun.spawnSync(['git', 'init', '-q'], { cwd: project })
  Bun.spawnSync(['git', 'config', 'user.email', 'test@example.invalid'], { cwd: project })
  Bun.spawnSync(['git', 'config', 'user.name', 'Test'], { cwd: project })
  Bun.spawnSync(['git', 'add', '.'], { cwd: project })
  Bun.spawnSync(['git', 'commit', '-qm', 'fixture'], { cwd: project })
  return project
}

async function exec(args, onAgent, options = {}) {
  const project = options.project || projectFor(options)
  const trace = { labels: [], prompts: {}, options: {} }
  const agent = async (prompt, agentOptions = {}) => {
    const label = agentOptions.label || ''
    trace.labels.push(label)
    trace.prompts[label] = prompt
    trace.options[label] = agentOptions
    const result = await onAgent(label, prompt, agentOptions)
    for (const path of result?.changedFiles || []) {
      const full = join(project, path)
      if (!existsSync(full)) {
        mkdirSync(dirname(full), { recursive: true })
        writeFileSync(full, `generated by ${label}\n`)
      }
    }
    return result
  }
  const parallel = async (thunks) => Promise.all(thunks.map(thunk => thunk()))
  const log = () => {}, phase = () => {}
  // PRODUCTION'S ACTUAL ENVIRONMENT. Claude Code never sets CLAUDE_SESSION_ID; the Workflow
  // runtime sees CLAUDE_CODE_SESSION_ID, which is the dispatching session's id. Setting the
  // variable the runner used to read is what hid the fact that it was always undefined in
  // production, where it reached .trim() and threw an uncaught TypeError.
  const originalStale = process.env.CLAUDE_SESSION_ID
  const originalSession = process.env.CLAUDE_CODE_SESSION_ID
  delete process.env.CLAUDE_SESSION_ID
  if (options.noSession) delete process.env.CLAUDE_CODE_SESSION_ID
  else process.env.CLAUDE_CODE_SESSION_ID = options.session || 'different-session'
  try {
    return {
      result: await runWorkflowModule(source, {
        agent, parallel, log, phase,
        args: { workflow: 'ds', ...args, projectDir: project },
      }),
      trace,
    }
  } finally {
    if (originalStale === undefined) delete process.env.CLAUDE_SESSION_ID
    else process.env.CLAUDE_SESSION_ID = originalStale
    if (originalSession === undefined) delete process.env.CLAUDE_CODE_SESSION_ID
    else process.env.CLAUDE_CODE_SESSION_ID = originalSession
    rmSync(project, { recursive: true, force: true })
  }
}

const task = (id, outputs, extra = {}) => ({
  id, name: `Task ${id}`, work: `Implement task ${id}.`, criteria: `Criterion ${id}.`,
  outputs, writablePaths: outputs, instructionFiles: ['/plugin/references/constraints/ds-common-constraints.md'],
  model: 'sonnet', effort: 'high', dependencyProof: 'independent', ...extra,
})

console.log('all implementation waves dispatch sequentially until filesystem isolation exists')
{
  const { result, trace } = await exec({ readyWave: [task('a', ['src/a.js']), task('b', ['src/b.js'])], planReset: reset }, label => ({ taskId: label.slice('implement:'.length), status: 'implemented', summary: 'done', reusableFacts: ['a fact'], changedFiles: label === 'implement:a' ? ['src/a.js'] : ['src/b.js'] }))
  ok('dispatches both tasks directly in deterministic order', trace.labels.join(',') === 'implement:a,implement:b', JSON.stringify(trace.labels))
  ok('uses conservative sequential mode', result.executionMode === 'sequential', result.executionReason)
  ok('passes task model', trace.options['implement:a']?.model === 'sonnet')
  ok('passes task effort', trace.options['implement:a']?.effort === 'high')
  ok('records implemented results', result.results.every(r => r.status === 'implemented'), JSON.stringify(result.results))
  ok('built-in dispatches carry task-specific captured approval evidence', result.results.every(r => /^[0-9a-f]{64}$/.test(r.approvalBundleDigest || '')), JSON.stringify(result.results))
  ok('returns reusable facts for caller curation', result.reusableFacts.length === 2, JSON.stringify(result.reusableFacts))
  ok('prompt includes only immutable filename/hash identity', new RegExp(hash).test(trace.prompts['implement:a']) && new RegExp(planFile).test(trace.prompts['implement:a']))
  ok('prompt excludes mutable planning files', !/STATE\.md|SPEC\.md|LEARNINGS\.md|agent-memory/.test(trace.prompts['implement:a']))
  ok('prompt requires caller-selected constraints', /ds-common-constraints\.md/.test(trace.prompts['implement:a']))
}

console.log('mutation snapshots reject non-regular entries without reading them')
if (process.platform !== 'win32') {
  const project = projectFor()
  Bun.spawnSync(['mkfifo', join(project, 'blocked.fifo')])
  const fifo = await exec({ readyWave: [task('a', ['allowed.txt'])], planReset: reset }, () => ({ taskId: 'a', status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: [] }), { project })
  ok('Git-backed observation does not claim ambient FIFO inventory', fifo.trace.labels.length === 1 && fifo.result.results[0].status === 'failed')

  const socketProject = projectFor()
  const server = createServer()
  await new Promise((resolve, reject) => server.listen(join(socketProject, 'blocked.sock'), resolve).once('error', reject))
  try {
    const socket = await exec({ readyWave: [task('a', ['allowed.txt'])], planReset: reset }, () => ({ taskId: 'a', status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: [] }), { project: socketProject })
    ok('Git-backed observation does not claim ambient socket inventory', socket.trace.labels.length === 1 && socket.result.results[0].status === 'failed')
  } finally { await new Promise(resolve => server.close(resolve)); rmSync(socketProject, { recursive: true, force: true }) }

  const created = projectFor()
  const { result } = await exec({ readyWave: [task('a', ['allowed.txt'])], planReset: reset }, () => {
    Bun.spawnSync(['mkfifo', join(created, 'created.fifo')])
    return { taskId: 'a', status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: [] }
  }, { project: created })
  ok('returns structured failure when required output is absent despite transient special entry', result.results[0].status === 'failed', JSON.stringify(result.results))
}

console.log('mutation observation is Git-backed, not an inline filesystem walk')
{
  // RE-DERIVED FROM THE DEAD SEAM'S FIRST CHECK. That check filtered `trace.snapshotReads` for
  // `/vendor/` paths and asserted zero — but the double that populated `snapshotReads` was installed
  // by a substitution that had stopped matching, so the array was empty for every input and the
  // assertion could not fail. There is no read seam to re-point at, because the property is now that
  // the runner performs NO reads: it delegates observation wholesale to captureGitObservation and
  // imports nothing from `node:fs`. Asserted against the shipped source, which is what a
  // reintroduced inline engine would have to change.
  ok('runner delegates observation to the Git-backed capture', /captureGitObservation\(PROJECT\)/.test(source))
  ok('runner has no inline recursive snapshot engine', !/\bnode:fs\b|\breaddirSync\b|\breadlinkSync\b/.test(source),
    (source.match(/\bnode:fs\b|\breaddirSync\b|\breadlinkSync\b/g) || []).join(','))
}
{
  // RE-DERIVED FROM THE DEAD SEAM'S SECOND CHECK, WITH A REAL FIXTURE INSTEAD OF A DOUBLE.
  //
  // The old check passed `freezeSnapshotMetadata: true` so `snapshotLstat` would hand back a frozen
  // mode/size for each path, forcing the then-inline snapshot to catch the mutation by CONTENT
  // rather than by metadata. The double was never installed, and the fixture's target was untracked
  // besides — Git re-reads untracked files unconditionally, so metadata could never have decided it.
  //
  // A same-signature mutation is directly constructible without any injection: rewrite a TRACKED
  // file to the same byte length and restore its mtime. That is the shape a stat cache would miss,
  // and it is the only shape where "hashes current bytes" is doing the work.
  //
  // The file must ALREADY be dirty before the run, and that detail is load-bearing rather than
  // incidental. A clean tracked file is absent from the pre-capture and present in the post-capture,
  // so the delta finds it by ENTRY PRESENCE and the content digest is never consulted — measured:
  // deleting `contentDigest` from git-observation's `logical()` left that version of this check
  // green. Dirtying it first puts an entry on both sides, so the digest is the only field that can
  // differ and the check fails when content hashing is removed.
  const project = projectFor()
  const target = join(project, 'tracked.txt')
  writeFileSync(target, 'commit')
  Bun.spawnSync(['git', 'add', 'tracked.txt'], { cwd: project })
  Bun.spawnSync(['git', 'commit', '-qm', 'tracked'], { cwd: project })
  writeFileSync(target, 'before')
  const original = lstatSync(target)
  const { result } = await exec({ readyWave: [task('a', ['src/a.js'])], planReset: reset }, () => {
    mkdirSync(join(project, 'src'), { recursive: true })
    writeFileSync(join(project, 'src/a.js'), 'produced')
    writeFileSync(target, 'after!')
    utimesSync(target, original.atime, original.mtime)
    return { taskId: 'a', status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: ['src/a.js'] }
  }, { project })
  const failed = result.results[0]
  // The declared output IS produced and IS reported, so a missing-output or report-mismatch failure
  // cannot stand in for the property under test: the only thing left to fail on is tracked.txt.
  ok('same-signature byte mutation is detected outside writable authority',
    failed.status === 'failed' && /outside writable authority/.test(failed.summary), JSON.stringify(failed))
  ok('same-signature byte mutation is named in the observed changes',
    (failed.observedChanges || []).includes('tracked.txt'), JSON.stringify(failed))
}

console.log('workflow authentication supports native-plan domains and rejects unsupported ones')
for (const workflow of ['dev', 'work', 'writing', 'workshop', 'workflow-creator']) {
  const project = projectFor({ workflow })
  const { result } = await exec({ workflow, readyWave: [task('a', ['src/a.js'])], planReset: reset }, label => ({ taskId: label.slice('implement:'.length), status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: ['src/a.js'] }), { project })
  ok(`${workflow} authenticates through shared approved-plan lifecycle`, result.results[0]?.status === 'implemented')
}
{
  let dispatched = false
  try {
    await exec({ workflow: 'unknown', readyWave: [], planReset: reset }, () => { dispatched = true; return null })
    ok('unsupported workflow without explicit policy rejected', false)
  } catch (error) { ok('unsupported workflow without explicit policy rejected before dispatch', !dispatched && /approvalMode/.test(String(error))) }
}
try {
  await exec({ workflow: 'workshop', readyWave: [], planReset: reset }, () => null)
  ok('cross-workflow metadata rejected', false)
} catch (error) { ok('cross-workflow receipt rejected', /review state|workflow/.test(String(error))) }
try {
  await exec({ workflow: 'ds', approvalPolicy: { schemaVersion: 1, workflow: 'ds', planPath: 'PLAN.md', metadataPath: 'PLAN.meta.json', verdictPath: 'PLAN_REVIEWED.md' }, readyWave: [], planReset: reset }, () => null)
  ok('built-in approval paths cannot be overridden', false)
} catch (error) { ok('built-in approval paths cannot be overridden', /cannot override/.test(String(error))) }
{
  const workflow = 'opaque-extension-7f3a'
  const project = mkdtempSync(join(tmpdir(), 'beat-implement-external-'))
  const approval = join(project, '.approval')
  const externalPlan = '# External approved plan\n'
  const externalHash = createHash('sha256').update(externalPlan).digest('hex')
  const approvalPolicy = {
    schemaVersion: 1,
    workflow,
    planPath: '.approval/CURRENT.md',
    metadataPath: '.approval/CURRENT.meta.json',
    verdictPath: '.approval/CURRENT_REVIEWED.md',
  }
  mkdirSync(approval, { recursive: true })
  writeFileSync(join(project, approvalPolicy.planPath), externalPlan)
  writeFileSync(join(project, approvalPolicy.metadataPath), JSON.stringify({
    schemaVersion: 1,
    workflow,
    planHash: externalHash,
    approvedSession: 'external-approval-session',
    approvedAt: '2026-01-01T00:00:00.000Z',
  }))
  writeFileSync(join(project, approvalPolicy.verdictPath), `---\nplan_hash: ${externalHash}\nstatus: APPROVED\nreviewer_session_id: external-review-session\nreviewed_at: 2026-01-01T00:00:01.000Z\n---\n`)
  Bun.spawnSync(['git', 'init', '-q'], { cwd: project })
  Bun.spawnSync(['git', 'config', 'user.email', 'test@example.invalid'], { cwd: project })
  Bun.spawnSync(['git', 'config', 'user.name', 'Test'], { cwd: project })
  Bun.spawnSync(['git', 'add', '.'], { cwd: project })
  Bun.spawnSync(['git', 'commit', '-qm', 'fixture'], { cwd: project })
  const { result } = await exec({
    workflow,
    approvalMode: 'external-fixed-v1',
    approvalPolicy,
    readyWave: [task('external', ['src/external.js'])],
    planReset: { approvedBodyHash: externalHash, session: 'external-approval-session' },
  }, () => ({ taskId: 'external', status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: ['src/external.js'] }), {
    project,
    session: 'external-implementation-session',
  })
  ok('external schema-v1 live approval dispatches without a captured bundle', result.results[0]?.status === 'implemented', JSON.stringify(result.results))
}

console.log('built-in generated-plan workflows reject caller-supplied captured bundles')
{
  let dispatched = false
  try {
    await exec({ workflow: 'ds', readyWave: [task('approved', ['src/approved.js'])], planReset: reset, capturedApprovalBundle: { schemaVersion: 1 } }, () => { dispatched = true; return {} })
    ok('built-in captured bundle rejected', false)
  } catch (error) { ok('built-in captured bundle rejected before dispatch', !dispatched && /do not accept captured approval bundles/.test(String(error))) }
}

console.log('durable plan review and reset gates reject invalid state')
for (const [name, options] of [
  ['stale plan review hash', { reviewHash: '0'.repeat(64) }],
  ['unapproved plan review', { reviewStatus: 'ISSUES_FOUND' }],
  ['reviewer approval session reused', { reviewerSession: 's-123' }],
  ['implementation session equals reviewer session', { session: 'reviewer-456' }],
  ['approval timestamp lacks UTC Z', { approvedAt: '2026-01-01T00:00:00+00:00' }],
  ['review timestamp lacks UTC Z', { reviewedAt: '2026-01-01T00:00:00+00:00' }],
  ['review predates approval', { approvedAt: '2026-01-01T00:01:00.000Z', reviewedAt: '2026-01-01T00:00:00.000Z' }],
  ['review equals approval timestamp', { approvedAt: '2026-01-01T00:00:00.000Z', reviewedAt: '2026-01-01T00:00:00.000Z' }],
  ['unexpected PLAN metadata key', { metaExtra: { forged: true } }],
]) {
  try {
    await exec({ readyWave: [task('a', ['src/a.js'])], planReset: reset }, () => ({}), options)
    ok(`rejects ${name}`, false)
  } catch { ok(`rejects ${name}`, true) }
}
// The runner is a DISPATCHER, not an implementer: it hands each task to an agent() subagent that
// gets its own identity. So the dispatching session may equal the approving session -- the
// single-conversation flow approves the plan and then dispatches -- while the REVIEWER must still
// differ from both. approver != implementer is enforced where the implementer's identity exists,
// on that subagent's own tool calls (see tests/implementer-identity-contract.test.mjs).
console.log('dispatch by the approving session is admitted; reviewer separation still holds')
{
  const { result } = await exec({ readyWave: [task('a', ['src/a.js'])], planReset: reset },
    async label => ({ taskId: label.slice('implement:'.length), status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: ['src/a.js'] }),
    { session: 's-123' })
  ok('approving session may dispatch implementation', result.results[0]?.status === 'implemented', JSON.stringify(result.results))
}
{
  const { result } = await exec({ readyWave: [task('a', ['src/a.js'])], planReset: reset },
    async label => ({ taskId: label.slice('implement:'.length), status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: ['src/a.js'] }),
    { session: 's-123', contextReset: true })
  ok('approving session may dispatch implementation with an irrelevant marker file present', result.results[0]?.status === 'implemented', JSON.stringify(result.results))
}

// F2: the runner read process.env.CLAUDE_SESSION_ID, which Claude Code never sets. That reached
// .trim() with no type guard and threw an uncaught TypeError out of the Workflow runtime instead
// of returning a controlled failure. With no identity available at all it must fail CLOSED with a
// clear message, and it must never crash.
console.log('the runner fails closed, never crashes, when it cannot authenticate its session')
{
  let message = ''
  try {
    await exec({ readyWave: [task('a', ['src/a.js'])], planReset: reset }, () => ({}), { noSession: true })
  } catch (error) { message = String(error) }
  ok('names the missing dispatching-session identity', /dispatch|session/i.test(message), message)
  ok('does not surface a TypeError', !/TypeError/.test(message), message)
}
{
  let message = ''
  try {
    await exec({ readyWave: [task('a', ['src/a.js'])], planReset: reset }, () => ({}), { session: '   ' })
  } catch (error) { message = String(error) }
  ok('rejects a blank dispatching-session identity', /dispatch|session/i.test(message) && !/TypeError/.test(message), message)
}

console.log('shared or ambiguous output tasks dispatch sequentially')
{
  const { trace } = await exec({ readyWave: [task('a', ['src/shared.js']), task('b', ['src/shared.js'])], planReset: reset }, async label => ({ taskId: label.slice('implement:'.length), status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: [] }))
  ok('shared outputs warn and use deterministic order', trace.labels.join(',') === 'implement:a,implement:b')
}
for (const [name, outputs] of [
  ['glob declaration', [['src/*.js'], ['src/a.js']]],
  ['directory declaration', [['src/'], ['src/a.js']]],
  ['traversal declaration', [['src/../src/a.js'], ['src/a.js']]],
]) {
  try {
    await exec({ readyWave: [task('a', outputs[0]), task('b', outputs[1])], planReset: reset }, () => ({}))
    ok(`rejects ${name}`, false)
  } catch { ok(`rejects ${name}`, true) }
}
{
  const { result } = await exec({ readyWave: [task('a', ['src/generated']), task('b', ['src/generated/types.ts'])], planReset: reset }, label => ({ taskId: label.slice('implement:'.length), status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: [] }))
  ok('ancestor overlaps descendant remains sequential', result.executionMode === 'sequential', result.executionReason)
}

console.log('writable path declarations enforce safe dispatch and result reporting')
for (const [name, writablePaths] of [
  ['traversal', ['src/../src/a.js']],
  ['absolute path', ['/tmp/a.js']],
  ['backslash path', ['src\\a.js']],
  ['glob', ['src/*.js']],
  ['directory', ['src/']],
]) {
  try {
    await exec({ readyWave: [task('a', ['src/a.js'], { writablePaths })], planReset: reset }, () => {
      throw new Error('invalid task must not dispatch an agent')
    })
    ok(`rejects ${name} writable path before agent invocation`, false)
  } catch { ok(`rejects ${name} writable path before agent invocation`, true) }
}
{
  const { result } = await exec({
    readyWave: [
      task('a', ['src/a.js'], { writablePaths: ['src/a.js', 'package.json'] }),
      task('b', ['src/b.js'], { writablePaths: ['src/b.js', 'package.json'] }),
    ], planReset: reset,
  }, label => ({ taskId: label.slice('implement:'.length), status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: [] }))
  ok('shared manifest writable path forces sequential dispatch', result.executionMode === 'sequential', result.executionReason)
}
{
  const { result } = await exec({ readyWave: [task('a', ['src/a.js'])], planReset: reset }, () => ({
    taskId: 'a', status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: ['package.json'],
  }))
  ok('undeclared changed file is rejected', result.results[0].status === 'failed')
}
{
  const project = projectFor()
  writeFileSync(join(project, 'src-a.js'), 'before')
  writeFileSync(join(project, 'src-b.js'), 'before')
  const { result } = await exec({ readyWave: [task('a', ['src-a.js', 'src-b.js'])], planReset: reset }, () => {
    writeFileSync(join(project, 'src-a.js'), 'after')
    writeFileSync(join(project, 'src-b.js'), 'after')
    return { taskId: 'a', status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: ['src-a.js', 'src-a.js'] }
  }, { project })
  ok('duplicate manifest entries cannot omit an observed change', result.results[0].status === 'failed', JSON.stringify(result.results))
}

console.log('failed output enforcement preserves post-dispatch mutation evidence and supersedes candidates')
{
  const eligibleCandidate = {
    manifestDigest: 'a'.repeat(64),
    status: 'eligible',
    releaseEligible: true,
    checks: { 'runner-floor': 'passed' },
    supersededManifestDigests: [],
  }
  const cases = [
    {
      name: 'unauthorized output',
      contract: task('a', ['src/a.js']),
      mutate(project) { writeFileSync(join(project, 'outside.js'), 'unauthorized') },
      reported: ['outside.js'],
      observed: ['outside.js'],
      error: /outside writable authority/,
    },
    {
      name: 'unexpected output',
      contract: task('a', ['src/a.js'], { writablePaths: ['src/a.js', 'src/extra.js'] }),
      mutate(project) {
        mkdirSync(join(project, 'src'), { recursive: true })
        writeFileSync(join(project, 'src/a.js'), 'expected')
        writeFileSync(join(project, 'src/extra.js'), 'unexpected')
      },
      reported: ['src/a.js', 'src/extra.js'],
      observed: ['src/a.js', 'src/extra.js'],
      error: /unexpected output/,
    },
    {
      name: 'missing output',
      contract: task('a', ['src/a.js'], { writablePaths: ['src/a.js', 'src/other.js'] }),
      mutate(project) {
        mkdirSync(join(project, 'src'), { recursive: true })
        writeFileSync(join(project, 'src/other.js'), 'other')
      },
      reported: ['src/other.js'],
      observed: ['src/other.js'],
      error: /required output/,
    },
    {
      name: 'duplicate report',
      contract: task('a', ['src/a.js']),
      mutate(project) {
        mkdirSync(join(project, 'src'), { recursive: true })
        writeFileSync(join(project, 'src/a.js'), 'changed')
      },
      reported: ['src/a.js', 'src/a.js'],
      observed: ['src/a.js'],
      error: /duplicate paths/,
    },
    {
      name: 'report mismatch',
      contract: task('a', ['src/a.js'], { writablePaths: ['src/a.js', 'src/other.js'] }),
      setup(project) {
        mkdirSync(join(project, 'src'), { recursive: true })
        writeFileSync(join(project, 'src/other.js'), 'preexisting')
      },
      mutate(project) {
        writeFileSync(join(project, 'src/a.js'), 'changed')
      },
      reported: ['src/other.js'],
      observed: ['src/a.js'],
      error: /report mismatch/,
    },
  ]
  for (const scenario of cases) {
    const project = projectFor()
    scenario.setup?.(project)
    const { result } = await exec({
      readyWave: [scenario.contract],
      planReset: reset,
      candidateState: eligibleCandidate,
      affectedChecks: ['runner-floor'],
    }, () => {
      scenario.mutate(project)
      return { taskId: 'a', status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: scenario.reported }
    }, { project })
    const failed = result.results[0]
    ok(`${scenario.name} remains the expected structured failure`, failed.status === 'failed' && scenario.error.test(failed.summary), JSON.stringify(failed))
    ok(`${scenario.name} retains truthful post-observation digest`, typeof failed.postObservationDigest === 'string' && failed.postObservationDigest !== failed.preObservationDigest, JSON.stringify(failed))
    ok(`${scenario.name} retains observed changes`, JSON.stringify(failed.observedChanges) === JSON.stringify(scenario.observed), JSON.stringify(failed))
    ok(`${scenario.name} retains changed files`, JSON.stringify(failed.changedFiles) === JSON.stringify(scenario.observed), JSON.stringify(failed))
    ok(`${scenario.name} supersedes the eligible candidate`, failed.candidateState?.status === 'superseded' && failed.candidateState.releaseEligible === false, JSON.stringify(failed))
  }
}

console.log('post-dispatch observation and supersession are mandatory on every dispatch outcome')
{
  const eligibleCandidate = {
    manifestDigest: 'b'.repeat(64),
    status: 'eligible',
    releaseEligible: true,
    checks: { 'runner-floor': 'passed' },
    supersededManifestDigests: [],
  }
  const project = projectFor()
  const { result } = await exec({
    readyWave: [task('a', ['src/a.js'])],
    planReset: reset,
    candidateState: eligibleCandidate,
    affectedChecks: ['runner-floor'],
  }, () => {
    mkdirSync(join(project, 'src'), { recursive: true })
    writeFileSync(join(project, 'src/a.js'), 'mutated before throw')
    throw new Error('agent transport exploded')
  }, { project })
  const failed = result.results[0]
  ok('throwing mutating agent remains failed', failed.status === 'failed' && /transport exploded/.test(failed.summary), JSON.stringify(failed))
  ok('throwing mutating agent retains truthful post digest', typeof failed.postObservationDigest === 'string' && failed.postObservationDigest !== failed.preObservationDigest, JSON.stringify(failed))
  ok('throwing mutating agent retains observed changes', JSON.stringify(failed.observedChanges) === JSON.stringify(['src/a.js']), JSON.stringify(failed))
  ok('throwing mutating agent supersedes candidate', failed.candidateState?.status === 'superseded' && failed.candidateState.releaseEligible === false, JSON.stringify(failed))
}
if (process.platform !== 'win32') {
  const eligibleCandidate = {
    manifestDigest: 'c'.repeat(64),
    status: 'eligible',
    releaseEligible: true,
    checks: { 'runner-floor': 'passed' },
    supersededManifestDigests: [],
  }
  const project = projectFor()
  const { result } = await exec({
    readyWave: [task('a', ['src/a.js'])],
    planReset: reset,
    candidateState: eligibleCandidate,
    affectedChecks: ['runner-floor'],
  }, () => {
    Bun.spawnSync(['mv', join(project, '.git'), join(project, '.git-hidden')])
    return { taskId: 'a', status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: [] }
  }, { project })
  const failed = result.results[0]
  ok('post-observation failure is structured and fail closed', failed.status === 'failed' && /post-dispatch observation failed/i.test(failed.summary), JSON.stringify(failed))
  ok('post-observation failure has no invented post digest', failed.postObservationDigest === undefined, JSON.stringify(failed))
  ok('post-observation failure makes candidate release-ineligible', failed.candidateState?.releaseEligible === false, JSON.stringify(failed))
}

console.log('candidate configuration is fully validated before dispatch')
for (const [name, candidateState, affectedChecks] of [
  ['blank affected check', { manifestDigest: 'd'.repeat(64), status: 'eligible', releaseEligible: true, checks: { tests: 'passed' }, supersededManifestDigests: [] }, ['']],
  ['unknown affected check', { manifestDigest: 'd'.repeat(64), status: 'eligible', releaseEligible: true, checks: { tests: 'passed' }, supersededManifestDigests: [] }, ['missing']],
  ['duplicate affected check', { manifestDigest: 'd'.repeat(64), status: 'eligible', releaseEligible: true, checks: { tests: 'passed' }, supersededManifestDigests: [] }, ['tests', 'tests']],
  ['stale affected check', { manifestDigest: 'd'.repeat(64), status: 'eligible', releaseEligible: true, checks: { tests: 'invalidated' }, supersededManifestDigests: [] }, ['tests']],
  ['malformed candidate state', { manifestDigest: 'not-a-digest', status: 'eligible', releaseEligible: true, checks: { tests: 'passed' }, supersededManifestDigests: [] }, ['tests']],
]) {
  let dispatched = false
  try {
    await exec({ readyWave: [task('a', ['src/a.js'])], planReset: reset, candidateState, affectedChecks }, () => { dispatched = true; return {} })
    ok(`rejects ${name}`, false)
  } catch { ok(`rejects ${name} without dispatch`, !dispatched) }
}

console.log('canonical writable paths reject symlink authority escapes')
{
  const external = mkdtempSync(join(tmpdir(), 'beat-implement-external-'))
  const project = projectFor()
  symlinkSync(external, join(project, 'allowed'))
  try {
    const { trace } = await exec({ readyWave: [task('a', ['allowed/file.js'])], planReset: reset }, () => ({}), { project })
    ok('rejects external directory symlink before dispatch', trace.labels.length === 0)
  } catch { ok('rejects external directory symlink before dispatch', true) }
  rmSync(external, { recursive: true, force: true })
}
for (const [name, target] of [['internal alias', 'real'], ['dangling alias', 'missing'], ['chained alias', 'middle']]) {
  const project = projectFor()
  if (name === 'internal alias') mkdirSync(join(project, 'real'))
  if (name === 'chained alias') symlinkSync('final', join(project, 'middle'))
  symlinkSync(target, join(project, 'allowed'))
  try {
    const { trace } = await exec({ readyWave: [task('a', ['allowed/file.js'])], planReset: reset }, () => ({}), { project })
    ok(`rejects ${name} before dispatch`, trace.labels.length === 0)
  } catch { ok(`rejects ${name} before dispatch`, true) }
}
{
  const project = projectFor()
  const { trace } = await exec({ readyWave: [task('a', ['safe/new/nested/file.js'])], planReset: reset }, () => ({ taskId: 'a', status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: [] }), { project })
  ok('allows safe non-existing nested writable path', trace.labels.join(',') === 'implement:a')
}
{
  const project = projectFor()
  mkdirSync(join(project, 'allowed'))
  const { result } = await exec({ readyWave: [task('a', ['allowed'])], planReset: reset }, () => {
    symlinkSync('elsewhere', join(project, 'allowed', 'reported'))
    return { taskId: 'a', status: 'implemented', summary: 'done', reusableFacts: [], changedFiles: ['allowed/reported/file.js'] }
  }, { project })
  ok('rejects reported path through a newly created symlink', result.results[0].status === 'failed')
}

console.log('resume includes only proven attempted work and preserves structured blocked records')
{
  const wave = [task('a', ['src/a.js']), task('b', ['src/b.js'])]
  const project = projectFor()
  const { result: initial } = await exec({ readyWave: wave, planReset: reset }, () => ({ taskId: 'a', status: 'failed', summary: 'previous attempt', reusableFacts: [], changedFiles: [] }), { project })
  // The first exec owns cleanup; make a fresh equivalent project for retry records.
  const { result, trace } = await exec({ readyWave: wave, planReset: reset, resume: { attemptedTaskIds: ['a'], attemptRecords: initial.results } }, label => ({ taskId: label.slice('implement:'.length), status: 'blocked', summary: 'needs decision', reusableFacts: ['blocking fact'], changedFiles: [] }))
  ok('only proven attempted task is resumed', trace.labels.join(',') === 'implement:a', JSON.stringify(trace.labels))
  ok('blocked result preserved', result.results.length === 1 && result.results[0].status === 'blocked', JSON.stringify(result.results))
}
for (const [name, attemptRecords] of [['no prior attempt proof', []], ['forged partial record', [{ taskId: 'a' }]]]) {
  try { await exec({ readyWave: [task('a', ['src/a.js'])], planReset: reset, resume: { attemptedTaskIds: ['a'], attemptRecords } }, () => ({})); ok(`rejects retry with ${name}`, false) } catch { ok(`rejects retry with ${name}`, true) }
}
{
  const wave = [task('a', ['src/a.js'])]
  const first = await exec({ workflow: 'work', readyWave: wave, planReset: reset }, () => ({ taskId: 'a', status: 'failed', summary: 'attempted', reusableFacts: [], changedFiles: [] }), { workflow: 'work' })
  const replacementPlan = '# Replacement approved plan\n'
  const replacementHash = createHash('sha256').update(replacementPlan).digest('hex')
  const replacementReset = { planFile: 'replacement-generated.md', planHash: replacementHash }
  let dispatched = false
  try {
    await exec({ workflow: 'work', readyWave: wave, planReset: replacementReset, resume: { attemptedTaskIds: ['a'], attemptRecords: first.result.results } }, () => { dispatched = true; return {} }, { workflow: 'work', plan: replacementPlan, planFile: 'replacement-generated.md', approvedSession: 's-456' })
    ok('work rejects retry records from a prior plan hash', false)
  } catch { ok('work rejects retry records from a prior plan hash before dispatch', !dispatched) }
}

console.log('plan-reset cross-check identity is strict')
for (const [name, badReset] of [['unexpected marker field', { ...reset, marker: true }], ['blank hash', { ...reset, planHash: '  ' }], ['object plan file', { ...reset, planFile: {} }]]) {
  try { await exec({ readyWave: [task('a', ['src/a.js'])], planReset: badReset }, () => ({})); ok(`rejects ${name}`, false) } catch { ok(`rejects ${name}`, true) }
}

console.log(`\n${PASS}/${PASS + FAIL} passed`)
if (FAIL) throw new Error(`${FAIL} beat-implement runner contract check(s) failed`)
