#!/usr/bin/env -S uv run --with lxml,pyyaml,pytest python3
"""Tests for scripts/prose-audit.py — the single deterministic prose/AI audit.

What is worth testing here is exactly what the consolidation promised and the four previous
loaders could not do:

  * ONE entry point covers every pattern system (scored tics, wikipedia-*, diction, stylometrics,
    the domain style guides);
  * overlapping hits COLLAPSE into one span at the highest contributing severity — the phrase
    `rich tapestry` reported three times under three labels is the bug this replaced;
  * the provenance-leak class is CAUGHT — `de_ai_audit.py`, the one script the prose reviewer was
    pointed at, missed every one of the seven artifacts asserted below;
  * all three document formats work, and footnotes are masked in each of them.

Run:  uv run --with lxml,pyyaml,pytest python3 -m pytest tests/test_prose_audit.py
"""
from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
AUDIT_PATH = REPO_ROOT / "scripts" / "prose-audit.py"
FIXTURES = REPO_ROOT / "tests" / "fixtures" / "prose-audit"


def _load():
    spec = importlib.util.spec_from_file_location("prose_audit", AUDIT_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


PA = _load()


# The .docx fixture is BUILT, not committed: a tracked binary needs a reviewed disposition in a
# candidate manifest (scripts/scan-public-privacy.ts), and generated bytes are reviewable besides.
_DOCX_BUILDER = importlib.util.spec_from_file_location("build_docx", FIXTURES / "build_docx.py")
_BUILD = importlib.util.module_from_spec(_DOCX_BUILDER)
_DOCX_BUILDER.loader.exec_module(_BUILD)
_DOCX = Path(tempfile.mkdtemp(prefix="prose-audit-fixture-")) / "manuscript.docx"
_BUILD.build(_DOCX)


def _fixture(name: str) -> Path:
    return _DOCX if name.endswith(".docx") else FIXTURES / name


def _audit(name: str, style: str | None = None) -> dict:
    return PA.audit_document(_fixture(name), style=style)


def _labels(res: dict) -> str:
    return " ".join(lab for s in res["spans"] for lab in s["labels"])


# ── C1: one entry point covers all five systems ──────────────────────────────
def test_every_pattern_system_is_represented():
    res = _audit("tics.md", style="legal")
    systems = {s["system"] for s in res["spans"]} | {
        sys_ for s in res["spans"] for sys_ in s["systems"]}
    for expected in ("scored-tic", "wikipedia-puffery", "wikipedia-promotional",
                     "wikipedia-communication", "wikipedia-chatgpt-artifacts",
                     "diction", "style", "writing-legal"):
        assert expected in systems, f"{expected} missing from {sorted(systems)}"


def test_domain_guide_is_gated_by_style():
    """Volokh is legal-only. Loading it for every draft is what the domain gate exists to stop."""
    general = {s["system"] for s in _audit("tics.md")["spans"]}
    legal = {s["system"] for s in _audit("tics.md", style="legal")["spans"]}
    assert "writing-legal" not in general
    assert "writing-legal" in legal


# ── C2: overlaps collapse ────────────────────────────────────────────────────
def test_overlap_collapses():
    """`rich tapestry` matches the sev4 scored tic, wikipedia-promotional AND diction always_flag.
    Before the consolidation that was three findings with three severities. It is one span."""
    res = _audit("tics.md")
    hits = [s for s in res["spans"] if s["quote"].lower() == "rich tapestry"]
    assert len(hits) == 1, hits
    span = hits[0]
    assert any("wikipedia-promotional" in lab for lab in span["labels"]), span["labels"]
    assert any("ai-tic·sev4·rich-tapestry" in lab for lab in span["labels"]), span["labels"]
    # Highest contributing severity wins: the scored tic is hard, the other two are soft.
    assert span["severity"] == "hard", span
    # The plain replacement survives the merge even though it came from the soft contributor.
    assert span["replace_with"], span


def test_unrelated_findings_on_one_line_stay_separate():
    """Collapse is by OVERLAPPING COLUMN RANGE, not by line. Two distinct phrases on the same
    line are two findings, and merging them would hide one."""
    res = _audit("tics.md")
    line3 = [s for s in res["spans"] if s["line"] == 3]
    assert len(line3) == 2, line3
    assert {s["quote"] for s in line3} == {"stands as a testament to", "plays a vital role"}


def test_cluster_diction_columns_are_line_relative(tmp_path):
    """A cluster-tier match is found in the whole PARAGRAPH, so its offset must be converted back
    to a column within its own line. It was not, so every match past the paragraph's first line
    landed at a column beyond the end of that line — mislocating the span AND, worse, silently
    missing the overlap with any other system that reported the same words at their real column."""
    draft = tmp_path / "cluster.md"
    draft.write_text("The board will galvanize the committee and\n"
                     "harness the cutting-edge disclosure regime today.\n")
    res = PA.audit_document(draft)
    hit = next(s for s in res["spans"] if any("cutting-edge" in lab for lab in s["labels"]))
    assert hit["line"] == 2
    assert hit["col"] == 13, hit          # "harness the cutting-edge…"
    # …and because the column is right, it collapses with wikipedia-promotional's own match.
    assert "wikipedia-promotional" in hit["systems"], hit
    assert len([s for s in res["spans"] if "cutting-edge" in s["quote"]]) == 1


def test_span_ids_are_stable_and_in_document_order():
    res = _audit("tics.md")
    assert [s["id"] for s in res["spans"]] == [f"S{i:03d}" for i in range(1, len(res["spans"]) + 1)]
    lines = [s["line"] for s in res["spans"] if s["line"]]
    assert lines == sorted(lines)
    # Same input, same ids — a reviewer citing S003 must mean the same span on a re-run.
    assert [s["id"] for s in _audit("tics.md")["spans"]] == [s["id"] for s in res["spans"]]


# ── C3: the coverage gap de_ai_audit.py left ─────────────────────────────────
# Every one of these was MISSED by de_ai_audit.py on this fixture, and de_ai_audit.py is the only
# scorer agents/writing-prose-reviewer.md ever pointed at. Four of the seven are hard.
_ARTIFACTS = [
    ("As an AI language model", "hard"),
    ("I hope this helps", "hard"),
    ("citeturn0search0", "hard"),
    ("oaicite", "hard"),
    ("stands as a testament", "hard"),   # sev4 scored tic
    ("plays a vital role", "soft"),
    ("Despite these challenges", "soft"),
]


@pytest.mark.parametrize(("needle", "severity"), _ARTIFACTS)
def test_provenance_and_puffery_artifacts_are_caught(needle, severity):
    res = _audit("tics.md")
    matched = [s for s in res["spans"]
               if needle.lower() in s["quote"].lower() or needle.lower() in s["context"].lower()]
    assert matched, f"{needle!r} not reported at all"
    assert any(s["severity"] == severity for s in matched), \
        f"{needle!r} reported at {[s['severity'] for s in matched]}, expected {severity}"


def test_de_ai_profile_really_does_miss_them():
    """The regression this whole consolidation exists to prevent, pinned as a fact rather than a
    claim: the de-ai profile is blind to the provenance-leak class, which is why nothing may point
    a reviewer at it alone."""
    de_ai = PA.de_ai_audit_file(str(FIXTURES / "tics.md"), ("always_flag", "cluster", "density"))
    # Compare against what the profile FLAGS (span text), not the whole payload — a stylometric
    # excerpt can quote an artifact incidentally without anyone having flagged it, which is
    # precisely the difference this test is about.
    flagged = " ".join(s["text"] for s in de_ai["spans"] if s["type"] != "style:nominalization").lower()
    for needle in ("as an ai language model", "oaicite", "plays a vital role", "i hope this helps"):
        assert needle not in flagged, f"de-ai profile unexpectedly caught {needle!r}"


# ── C6: three formats ────────────────────────────────────────────────────────
@pytest.mark.parametrize("fixture", ["tics.md", "letter.typ", "manuscript.docx"])
def test_all_three_formats_produce_spans(fixture):
    res = _audit(fixture)
    assert res["spans"], f"{fixture} produced no spans"
    assert res["n_hard"] > 0, f"{fixture} produced no hard spans"


@pytest.mark.parametrize(("fixture", "needle"), [
    ("tics.md", "rich tapestry of citations"),        # pandoc ^[...] inline footnote
    ("tics.md", "reference footnote"),                # markdown [^id]: definition
    ("letter.typ", "rich tapestry of citations"),     # Typst #footnote[...]
    ("manuscript.docx", "footnote that is itself"),   # docx word/footnotes.xml
])
def test_footnotes_are_masked_in_every_format(fixture, needle):
    res = _audit(fixture)
    for span in res["spans"]:
        assert needle.lower() not in span["context"].lower(), \
            f"{fixture}: finding landed inside a footnote — {span}"


def test_keep_footnotes_proves_masking_is_what_suppresses_them():
    masked = PA.audit_document(FIXTURES / "tics.md", mask=True)
    kept = PA.audit_document(FIXTURES / "tics.md", mask=False)
    assert len(kept["spans"]) > len(masked["spans"])
    assert "reference footnote" in _labels(kept) + " ".join(s["context"] for s in kept["spans"])


def test_em_dash_density_counts_body_prose_only(tmp_path):
    """The em-dash budget was carried over from the deleted writing-ai-smell-em-dash constraint,
    INCLUDING its exclusions. Frontmatter, fenced code, blockquotes (quoted source material) and
    HTML comments are not the author's prose, and charging their dashes to the author's budget is
    the false positive the original spent its whole `_prose_paragraphs` scanner avoiding."""
    draft = tmp_path / "dashes.md"
    draft.write_text(
        "---\ntitle: A — B — C — D — E\n---\n\n"
        "> The court said — and this matters — that the rule — as written — fails.\n\n"
        "```\ncode — with — many — em — dashes — here\n```\n\n"
        "<!-- editorial — note — with — dashes — inside -->\n\n"
        "Body text with one — dash.\n"
    )
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if s["system"] == "em-dash"], res["spans"]

    # …and the budget still fires on real body prose.
    loud = tmp_path / "loud.md"
    loud.write_text("The rule — as written — fails, and the staff — who drafted it — knew.\n")
    assert [s for s in PA.audit_document(loud)["spans"] if s["system"] == "em-dash"]


# ── markup is not prose, and it must never reach the HARD class ──────────────
def test_typst_inline_markup_is_not_a_placeholder(tmp_path):
    """THE MEASURED FALSE POSITIVE, pinned. `#emph[First],` in a real Typst comment letter matched
    the `[Name]`-style placeholder rule — which is SEVERITY = hard, and the reviewer prompt calls a
    hard span "a provenance leak … almost never defensible". Ordinary emphasis in a regulatory
    filing was being injected into three reviewers as high-confidence evidence of AI authorship."""
    draft = tmp_path / "letter.typ"
    draft.write_text(
        "#set page(margin: 1in)\n"
        "\n"
        "There are two reasons. #emph[First], the statistic is constructed oddly.\n"
        "#emph[Second], the natural experiment says otherwise.\n"
    )
    res = PA.audit_document(draft)
    assert res["n_hard"] == 0, [s for s in res["spans"] if s["severity"] == "hard"]
    assert not [s for s in res["spans"] if "placeholder" in " ".join(s["labels"])], res["spans"]


def test_typst_neutralisation_keeps_the_prose_and_the_offsets(tmp_path):
    """Blanking the DELIMITERS and keeping the content is the point: `First` is a word the author
    wrote. It also recovers prose that was being dropped entirely — prose_extract skips a Typst
    line STARTING with `#`, so a paragraph opening `#emph[First],` never reached any scorer."""
    src = "#emph[First], the market is a rich tapestry of incentives.\n"
    out = PA.neutralize_typst_markup(src)
    assert len(out) == len(src) and out.count("\n") == src.count("\n")
    assert "First" in out and "#emph[" not in out

    draft = tmp_path / "recovered.typ"
    draft.write_text(src)
    res = PA.audit_document(draft)
    assert [s for s in res["spans"] if s["quote"].lower() == "rich tapestry"], res["spans"]


def test_typst_code_lines_are_still_skipped(tmp_path):
    """The neutraliser fires only on `#name[`, so `#let` / `#set` / `#import` stay code and stay
    skipped. Loosening that would pour a `#let` dictionary's contents into the prose scan."""
    draft = tmp_path / "code.typ"
    draft.write_text(
        '#import "@preview/letter:0.1.0": letter\n'
        "#let recipient = (\n"
        '  name: "A Delaware Court",\n'
        ")\n"
        "Real prose here.\n"
    )
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if "Delaware" in s["context"]], res["spans"]


def test_keep_footnotes_does_not_reinstate_the_markup_false_positive(tmp_path):
    """`--keep-footnotes` debugs the raw PROSE signal. Markup was never part of that signal, so it
    is neutralised on both paths — otherwise the flag quietly brings the hard FP back."""
    draft = tmp_path / "letter.typ"
    draft.write_text("There are two reasons. #emph[First], the statistic is odd.\n")
    assert PA.audit_document(draft, mask=False)["n_hard"] == 0


def test_nested_typst_markup_closes_on_the_right_bracket():
    out = PA.neutralize_typst_markup("#emph[a #strong[b] c] tail")
    assert "#emph[" not in out and "#strong[" not in out
    assert "a" in out and "b" in out and "c" in out and out.endswith("tail")


def test_latex_markup_is_neutralised_too():
    """`.tex` has no dedicated extractor, so without this every command is scored as the author's
    own words — the same class of defect the Typst case proved."""
    out = PA.neutralize_latex_markup("\\emph{First}, see \\cite[p. 5]{smith2019} and \\begin{quote}\n")
    assert "\\emph" not in out and "\\cite" not in out and "\\begin" not in out
    assert "First" in out and "smith2019" in out  # content kept, wrapper gone


def test_unbalanced_markup_does_not_eat_the_document():
    """An opener with no closer blanks only its head. Swallowing to end-of-file would silently
    blank the rest of a draft and report it clean."""
    out = PA.neutralize_typst_markup("#emph[unclosed and then more prose about a rich tapestry")
    assert "rich tapestry" in out and "#emph" not in out


# ── severity is a property of the source table, not of this script ───────────
def test_hard_is_only_the_zero_false_positive_classes():
    res = _audit("tics.md", style="legal")
    for span in res["spans"]:
        if span["severity"] != "hard":
            continue
        assert any(
            lab.startswith(("wikipedia-chatgpt-artifacts", "wikipedia-template-artifacts",
                            "wikipedia-communication", "ai-tic·sev4", "ai-tic·sev5",
                            # `formatting·emoji` earns hard by construction, not by a corpus
                            # sweep: an emoji in a law-review draft is indefensible on its face.
                            "formatting·emoji"))
            for lab in span["labels"]), span


# ── emphasis: markup as a SIDE CHANNEL, format-agnostic ──────────────────────
# THE THREE STACKED FAILURES THIS PINS. Before v5.134.0 a Typst document could carry arbitrary
# boldface through a full writing-review pass unremarked, because (1) the only bold rule scanned
# `<cwd>/drafts/*.md`, (2) its regex was markdown-only, and (3) neutralisation had already blanked
# the markup before any scorer ran. Fixing 1 and 2 without 3 buys nothing, which is why the spans
# are harvested from the raw text and carried alongside instead of being re-derived from prose.
#
# GOLDEN FIXTURES, NOT THE CORPUS. The FP hunt ran against `~/projects/{opv,mirror,rule611}` Typst
# sources, which live outside this repo; machine-specific paths must not enter the suite. Results
# are recorded in docs/investigations/2026-08-05_emphasis-enforcement.md.
_BOLD_LEAD_SOURCES = [
    (".typ", "#strong[The objection.] A five percent stake could leverage mirror voting.\n"),
    (".tex", "\\textbf{The objection.} A five percent stake could leverage mirror voting.\n"),
    (".md", "**The objection.** A five percent stake could leverage mirror voting.\n"),
]


@pytest.mark.parametrize(("suffix", "src"), _BOLD_LEAD_SOURCES)
def test_bold_lead_is_flagged_in_every_text_format(tmp_path, suffix, src):
    draft = tmp_path / f"lead{suffix}"
    draft.write_text(src)
    res = PA.audit_document(draft)
    hits = [s for s in res["spans"] if s["system"] == "emphasis"]
    assert any("bold-lead" in lab for s in hits for lab in s["labels"]), res["spans"]
    assert hits[0]["line"] == 1 and hits[0]["col"] == 1, hits


@pytest.mark.parametrize(("suffix", "src"), [
    (".typ", "+ #strong[Market mirroring.] The block votes For and Against in proportion.\n"),
    (".md", "- **Market mirroring.** The block votes For and Against in proportion.\n"),
    (".md", "1. **Market mirroring.** The block votes For and Against in proportion.\n"),
])
def test_list_items_are_exempt_from_bold_lead(tmp_path, suffix, src):
    """APPROVED DECISION, and a measured one. mirror/paper/typst/body.typ:161-169 is a numbered
    scenario list whose items open `+ #strong[Market mirroring.]`. A numbered list of defined
    scenarios is not an inline-header paragraph, and flagging it would make the rule unusable on
    the one local source that carries the most emphasis."""
    draft = tmp_path / f"list{suffix}"
    draft.write_text(src)
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if "bold-lead" in " ".join(s["labels"])], res["spans"]


def test_exhibit_captions_are_exempt_from_bold_lead(tmp_path):
    """FOUND BY THE FP HUNT: `#strong[Table 1:] Headline reform comparison…` accounted for ALL
    FIVE out-of-table bold-lead hits in mirror/paper/typst/body.typ. A caption label is not an
    inline header, and it is excluded by shape rather than by lowering the bar."""
    draft = tmp_path / "caption.typ"
    draft.write_text("#strong[Table 1:] Headline reform comparison across four block levels\n"
                     "\n"
                     "#strong[Figure 2.] Mirror pro-rata flips by vote category\n")
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if "bold-lead" in " ".join(s["labels"])], res["spans"]


def test_table_cells_are_exempt_from_every_bold_rule(tmp_path):
    """NOT AN OPTIMISATION — the thing that makes the bold rules viable. mirror's 258 `#strong[]`
    spans are overwhelmingly table header cells; without this a correctly formatted results table
    reads as bold saturation."""
    draft = tmp_path / "table.typ"
    draft.write_text(
        "#table(\n"
        "  columns: 3,\n"
        "  #strong[Items], #strong[Flips], #strong[(%)],\n"
        "  [Say on pay], #strong[2,070], #strong[0.40%],\n"
        ")\n")
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if s["system"] == "emphasis"], res["spans"]


@pytest.mark.parametrize(("suffix", "src"), [
    (".typ", "The market saw #strong[546,088] trades and #strong[63% more] volume overall.\n"),
    (".tex", "The market saw \\textbf{546,088} trades and \\textbf{63\\% more} volume.\n"),
    (".md", "The market saw **546,088** trades and **63% more** volume overall today.\n"),
])
def test_bold_on_a_bare_number_is_flagged_in_every_text_format(tmp_path, suffix, src):
    draft = tmp_path / f"num{suffix}"
    draft.write_text(src)
    res = PA.audit_document(draft)
    quoted = {s["quote"] for s in res["spans"]
              if "bold-bare-number" in " ".join(s["labels"])}
    assert "546,088" in quoted, res["spans"]


def test_bold_on_a_claim_is_not_a_bare_number(tmp_path):
    """The rule is `emphasise the claim, not the digits`, so the claim itself must pass."""
    draft = tmp_path / "claim.typ"
    draft.write_text("The market saw #strong[546,088 trades] under the proposed rule.\n")
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if "bold-bare-number" in " ".join(s["labels"])], res["spans"]


def test_bold_density_needs_a_document(tmp_path):
    """`mirror/paper/typst/style.typ` is a template with one prose word in it. One bold span over
    one word is 1,000 per 1,000 — an arithmetic artifact, not saturation."""
    draft = tmp_path / "style.typ"
    draft.write_text("#let x = 1\n#strong[Note]\n")
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if "bold-density" in " ".join(s["labels"])], res["spans"]


def test_bold_density_fires_over_the_budget(tmp_path):
    draft = tmp_path / "loud.typ"
    body = " ".join(f"Word{i}" for i in range(400))
    draft.write_text(body + "\n\n" + "\n".join(
        f"Sentence {i} reports #strong[a finding] about the market." for i in range(20)))
    res = PA.audit_document(draft)
    hits = [s for s in res["spans"] if "bold-density" in " ".join(s["labels"])]
    assert hits and hits[0]["line"] == 0, res["spans"]


def test_strong_inside_a_typst_footnote_is_never_collected(tmp_path):
    """Footnote masking runs FIRST, for the same reason it runs first before neutralisation: a
    finding must never land inside a note."""
    draft = tmp_path / "fn.typ"
    draft.write_text("The rule applies.#footnote[See #strong[546,088] trades in the record.]\n")
    _, _, spans = PA.extract_lines(draft)
    assert not spans, spans


def test_emphasis_collection_survives_neutralisation(tmp_path):
    """The regression the whole side-channel design exists to prevent: the scorers still see
    neutralised text (markup blanked, prose kept), and the emphasis spans exist anyway."""
    draft = tmp_path / "both.typ"
    draft.write_text("The market saw #strong[546,088] trades and #emph[substantial] growth.\n")
    lines, masked, spans = PA.extract_lines(draft)
    assert "#strong[" not in masked and "546,088" in masked   # neutralisation unchanged
    assert [s["kind"] for s in spans] == ["strong", "emph"]
    assert spans[0]["text"] == "546,088"


def test_emphasis_does_not_reinstate_the_v5127_hard_false_positive(tmp_path):
    """PINNED. `#emph[First],` matched wikipedia-template-artifacts' `[Name]` placeholder rule — a
    HARD span the reviewer prompt calls "almost never defensible". Harvesting emphasis must not
    bring it back by any route, and emphasis findings are soft besides."""
    draft = tmp_path / "letter.typ"
    draft.write_text(
        "There are two reasons. #emph[First], the statistic is constructed oddly.\n"
        "#emph[Second], the natural experiment says otherwise.\n")
    res = PA.audit_document(draft)
    assert res["n_hard"] == 0, [s for s in res["spans"] if s["severity"] == "hard"]
    assert not [s for s in res["spans"] if "placeholder" in " ".join(s["labels"])], res["spans"]
    assert all(s["severity"] == "soft" for s in res["spans"] if s["system"] == "emphasis")


def test_docx_emphasis_is_deferred_not_silently_wrong(tmp_path):
    """`.docx` bold runs are out of scope, and the contract says so explicitly rather than
    implying it: no emphasis spans, no crash."""
    lines, masked, spans = PA.extract_lines(_DOCX)
    assert masked is None and spans == [] and lines


# ── emojis: the one hard rule here ───────────────────────────────────────────
def test_emoji_in_prose_is_hard(tmp_path):
    draft = tmp_path / "emoji.md"
    draft.write_text("The agency responded quickly 🚨 and the staff agreed.\n")
    res = PA.audit_document(draft)
    hits = [s for s in res["spans"] if s["system"] == "formatting"]
    assert hits and hits[0]["severity"] == "hard", res["spans"]
    assert hits[0]["line"] == 1


def test_emoji_inside_a_fence_or_quote_is_clean(tmp_path):
    """Same exclusions as the em-dash budget: a fenced code block and a quoted source are not the
    author's prose, and a HARD rule may not fire on them."""
    draft = tmp_path / "fenced.md"
    draft.write_text("```\nprint('🚨 alert')\n```\n\n> The filing said 🚨 loudly.\n\nBody text.\n")
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if s["system"] == "formatting"], res["spans"]


@pytest.mark.parametrize("ch", ["×", "—", "§", "†", "‡", "✓", "✔"])
def test_typographic_characters_are_not_emojis(tmp_path, ch):
    """A `hard` rule may not fire on a multiplication sign, an em dash, a section mark, a dagger
    or a checkmark in a comparison table. The VS16 emoji-presentation forms still match."""
    draft = tmp_path / "typo.md"
    draft.write_text(f"The ratio is 1.60{ch} across every specification in the table.\n")
    res = PA.audit_document(draft)
    assert not [s for s in res["spans"] if s["system"] == "formatting"], res["spans"]


def test_emoji_in_a_slide_deck_is_soft_not_hard(tmp_path):
    """A deck is not a draft and emoji in one are deliberate. The hook refuses to lint a deck at
    all; this covers the case it cannot — auditing a deck ON PURPOSE from the CLI. The finding
    survives (you asked for the audit) but may not block a gate."""
    deck = tmp_path / "08.typ"
    deck.write_text('#slide(title: "Insider trading")[\n  The rule bites 🚨 here.\n]\n')
    res = PA.audit_document(deck)
    hits = [s for s in res["spans"] if s["system"] == "formatting"]
    assert hits, res["spans"]
    assert hits[0]["severity"] == "soft", hits
    assert res["n_hard"] == 0, [s for s in res["spans"] if s["severity"] == "hard"]

    # …and the identical content outside a deck is still hard.
    draft = tmp_path / "letter.typ"
    draft.write_text("#set page(margin: 1in)\n\nThe rule bites 🚨 here.\n")
    assert [s for s in PA.audit_document(draft)["spans"]
            if s["system"] == "formatting" and s["severity"] == "hard"]


def test_deck_detection_matches_the_hooks_rules(tmp_path):
    """`is_deck` mirrors `isTypDeck` in hooks/writing-prose-check.ts. The cross-LANGUAGE agreement
    is pinned in tests/writing-prose-check.test.mjs; this pins the Python side's own rules."""
    slides = tmp_path / "slides" / "03-security"
    slides.mkdir(parents=True)
    by_dir = slides / "08.typ"
    by_dir.write_text("Dear Professor,\n")            # no marker at all
    assert PA.is_deck(by_dir)
    for marker in ('#import "@preview/touying:0.5.0": *\n',
                   '#import "@preview/polylux:0.3.1": *\n',
                   '#slide(title: "x")[ y ]\n'):
        f = tmp_path / "theme.typ"
        f.write_text(marker)
        assert PA.is_deck(f), marker
    letter = tmp_path / "letter.typ"
    letter.write_text("#set page(margin: 1in)\nDear Professor,\nSincerely.\n")
    assert not PA.is_deck(letter)
    md = tmp_path / "slides" / "notes.md"
    md.write_text("#slide(\n")
    assert not PA.is_deck(md), "only .typ can be a deck"


# ── the CLI contract the hook and the reviewers depend on ────────────────────
def test_cli_json_and_exit_code():
    proc = subprocess.run(
        [sys.executable, str(AUDIT_PATH), "--json", "--style", "legal", str(FIXTURES / "tics.md")],
        capture_output=True, text=True, check=False)
    assert proc.returncode == 1, proc.stderr           # hard spans present
    payload = json.loads(proc.stdout)
    assert payload["spans"][0]["id"] == "S001"
    assert {"id", "line", "col", "system", "labels", "severity", "quote", "replace_with"} \
        <= set(payload["spans"][0])


def test_cli_exits_zero_on_soft_only_prose(tmp_path):
    """Only `hard` may block a gate, and the exit code says so."""
    draft = tmp_path / "soft.md"
    draft.write_text("Despite these challenges, the agency proceeded with the rule.\n")
    proc = subprocess.run(
        [sys.executable, str(AUDIT_PATH), "--json", str(draft)],
        capture_output=True, text=True, check=False)
    assert proc.returncode == 0, proc.stdout
    payload = json.loads(proc.stdout)
    assert payload["spans"] and payload["n_hard"] == 0


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-q"]))
