#!/usr/bin/env python3
"""
Inventory all accessible WRDS PostgreSQL schemas, their tables, and row counts.
Output is markdown suitable for pasting into SKILL.md or a reference doc.

Usage:
    pixi run python skills/wrds/scripts/inventory_schemas.py
    pixi run python skills/wrds/scripts/inventory_schemas.py --json > wrds_schemas.json
"""

import sys
import json
import argparse
import psycopg2

EXCLUDED_SCHEMAS = {
    'pg_catalog', 'information_schema', 'pg_toast',
    'pg_temp_1', 'pg_toast_temp_1', 'public',
}


def get_connection():
    return psycopg2.connect(
        host='wrds-pgdata.wharton.upenn.edu',
        port=9737,
        database='wrds',
        user='eddyhu',
        sslmode='require'
    )


def inventory(conn):
    cur = conn.cursor()

    # All accessible schemas
    cur.execute("""
        SELECT schema_name
        FROM information_schema.schemata
        WHERE schema_name NOT LIKE 'pg_%'
          AND schema_name != 'information_schema'
        ORDER BY schema_name
    """)
    schemas = [r[0] for r in cur.fetchall() if r[0] not in EXCLUDED_SCHEMAS]
    print(f"Found {len(schemas)} schemas", file=sys.stderr)

    result = {}
    for schema in schemas:
        # Tables + approx row counts via pg_stat_user_tables (fast, no full scan)
        cur.execute("""
            SELECT
                t.table_name,
                COALESCE(s.n_live_tup, -1)            AS approx_rows,
                pg_size_pretty(
                    pg_total_relation_size(
                        quote_ident(t.table_schema) || '.' ||
                        quote_ident(t.table_name)
                    )
                )                                      AS size
            FROM information_schema.tables t
            LEFT JOIN pg_stat_user_tables s
                ON s.schemaname = t.table_schema
               AND s.relname    = t.table_name
            WHERE t.table_schema = %s
              AND t.table_type   = 'BASE TABLE'
            ORDER BY approx_rows DESC NULLS LAST, t.table_name
        """, (schema,))
        tables = cur.fetchall()
        if tables:
            result[schema] = [
                {'table': t, 'approx_rows': r, 'size': s}
                for t, r, s in tables
            ]
            print(f"  {schema}: {len(tables)} tables", file=sys.stderr)

    return result


def render_markdown(data):
    lines = ['# WRDS Schema Inventory\n',
             '> Auto-generated by `scripts/inventory_schemas.py`\n']

    for schema, tables in sorted(data.items()):
        lines.append(f'\n## `{schema}`\n')
        lines.append('| Table | Approx Rows | Size |')
        lines.append('|-------|------------|------|')
        for t in tables:
            rows = f"{t['approx_rows']:,}" if t['approx_rows'] >= 0 else '—'
            lines.append(f"| `{t['table']}` | {rows} | {t['size']} |")

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--json', action='store_true', help='Output JSON instead of Markdown')
    args = parser.parse_args()

    conn = get_connection()
    print("Connected to WRDS", file=sys.stderr)

    data = inventory(conn)
    conn.close()

    if args.json:
        print(json.dumps(data, indent=2))
    else:
        print(render_markdown(data))


if __name__ == '__main__':
    main()
