#!/usr/bin/env -S uv run python3
"""
ds-compile: deterministically compile a ds PLAN.md Task Breakdown table into a
lean, project-specific Workflow script (.planning/run.js) from the shared template.

NO LLM. This replaces ds-implement.js's per-call LLM "discovery" agent (and the one
misparse it produced). Parsing is via the shared tolerant parser ds_plan_table.py
(the same module the executable guard uses), so compile and gate never disagree.

Usage:
  ds_compile.py PLAN.md [--out RUN_JS] [--project DIR] [--template TPL]

Defaults: --out  <PLAN dir>/run.js
          --project  parent of the .planning dir holding PLAN.md
          --template workflows/templates/ds-run-template.js (resolved from this file)

Exit 0 on success; non-zero (with violations on stderr) if the plan is not compilable.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ds_plan_table import parse_plan, toposort, Task  # noqa: E402

_HERE = Path(__file__).resolve()
_DEFAULT_TEMPLATE = _HERE.parents[2] / "workflows" / "templates" / "ds-run-template.js"


def _tier(t: Task) -> tuple[str, str]:
    """Heuristic model tier + effort (v1; overridable later via a Tip/Tier column).
    engineer/heavy → sonnet; trivial mechanical → haiku; methodology/pause → sonnet."""
    text = (t.task_text or "").lower()
    heavy = t.kind == "engineer" or any(
        o.endswith((".parquet", ".parquet`")) or "master" in o.lower() for o in (t.outputs or []))
    trivial = (
        t.kind != "engineer"
        and len(t.outputs) <= 1
        and any(k in text for k in ("loader", "thin ", "caption", "rename", "wire the notebook", "import"))
        and "regression" not in text and "winsor" not in text
    )
    if t.pause_after or any(k in text for k in ("methodology", "method-", "r4b", "decide", "winsor")):
        return "sonnet", "high"
    if heavy:
        return "sonnet", "medium"
    if trivial:
        return "haiku", "low"
    return "sonnet", "medium"


def _spec_dict(t: Task) -> dict:
    tier, effort = _tier(t)
    return {
        "id": t.id, "name": t.name, "kind": t.kind, "deps": t.deps,
        "outputs": t.outputs, "expectedOutput": t.expected_output,
        "verify": t.verify, "implements": t.implements, "done": t.done,
        "pauseAfter": t.pause_after, "taskText": t.task_text,
        "tier": tier, "effort": effort,
    }


def _js_literal(value) -> str:
    """JSON is a subset of JS object/array literal syntax — safe to inject."""
    return json.dumps(value, ensure_ascii=False, indent=2)


def compile_plan(plan_path: Path, out_path: Path, project_dir: Path, template_path: Path) -> int:
    text = plan_path.read_text()
    res = parse_plan(text)
    if not res.ok:
        print("PLAN NOT COMPILABLE:\n- " + "\n- ".join(res.violations), file=sys.stderr)
        return 1

    specs = [_spec_dict(t) for t in res.tasks]
    levels = toposort(res.tasks)
    pauses = [s["id"] for s in specs if s["pauseAfter"]]

    meta = {
        "name": "ds-run",
        "description": (
            f"Compiled ds runner for {project_dir.name}: topo-runs {len(specs)} task(s) across "
            f"{len(levels)} dependency level(s) with real parallelism, output-first, gating each on "
            f"its Verify exit code (independent probe), pausing at decisions. Generated by ds-compile "
            f"from PLAN.md — do not hand-edit; edit PLAN.md and recompile."),
        "phases": [{"title": f"Level {i}", "detail": " ".join(levels[i])} for i in range(len(levels))]
                  + [{"title": "Gate", "detail": "independent probe of each Verify exit code"}],
    }

    template = template_path.read_text()
    holes = {"/*__META__*/": _js_literal(meta),
             "/*__PROJECT__*/": json.dumps(str(project_dir)),
             "/*__TASKS__*/": _js_literal(specs)}
    for hole in holes:
        n = template.count(hole)
        if n != 1:
            print(f"Template {template_path}: hole {hole} appears {n}× (expected exactly 1). "
                  f"A hole token must not appear in documentation/comments.", file=sys.stderr)
            return 2

    banner = (
        "// GENERATED by ds-compile from PLAN.md — DO NOT EDIT. Edit PLAN.md and recompile.\n"
        f"// source: {plan_path}\n"
        f"// tasks: {len(specs)} | levels: {len(levels)} | declared pauses: {pauses or 'none'}\n\n")
    out = banner + template
    for hole, repl in holes.items():
        out = out.replace(hole, repl, 1)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out)
    print(f"compiled {len(specs)} task(s), {len(levels)} level(s) → {out_path}")
    if pauses:
        print(f"  declared pause(s) at: {', '.join(pauses)}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("plan")
    ap.add_argument("--out")
    ap.add_argument("--project")
    ap.add_argument("--template", default=str(_DEFAULT_TEMPLATE))
    a = ap.parse_args()

    plan_path = Path(a.plan).resolve()
    if not plan_path.is_file():
        print(f"PLAN.md not found: {plan_path}", file=sys.stderr)
        return 2
    out_path = Path(a.out).resolve() if a.out else plan_path.parent / "run.js"
    # project dir = parent of .planning (or PLAN's dir if not under .planning)
    if a.project:
        project_dir = Path(a.project).resolve()
    else:
        p = plan_path.parent
        project_dir = p.parent if p.name == ".planning" else p
    return compile_plan(plan_path, out_path, project_dir, Path(a.template).resolve())


if __name__ == "__main__":
    sys.exit(main())
