#!/usr/bin/env python3
"""emit-registers — ONE source per domain, three output styles and one preloadable skill.

    references/registers/{general,legal,econ}.md      SOURCE OF TRUTH (hand-edited)
            |
            +-- output-styles/{general-prose,law-review,econ-journal}.md   main conversation
            +-- skills/writing-register/SKILL.md                            subagent preload

WHY A GENERATOR AND NOT THREE HAND-MAINTAINED COPIES. The same register facts have to reach three
different surfaces with three different delivery mechanisms, and the mechanisms are not
substitutable:

  * An OUTPUT STYLE shapes the main conversation and reaches no subagent at all. A subagent runs its
    own system prompt; the docs are explicit that the main conversation's output style does not
    shape it.
  * A PRELOADED SKILL (`skills:` in agent frontmatter) reaches a subagent and is the ONLY channel
    that reaches one whose `tools` list omits `Skill` — which `writing-prose-reviewer` does.
  * Neither can vary by domain at dispatch time, because `skills:` frontmatter is static. So the
    preloaded artifact is ONE combined file carrying all three registers contrastively, and the
    dispatch prompt names which one applies.

Three copies of the same table drift, and the drift is silent because nothing reads all three at
once. `--check` is the same shape as `scripts/bump-version.sh --check`: it regenerates in memory and
exits 1 if any generated file differs from what the sources say it should be.

Usage:
  emit-registers.py            # regenerate every artifact
  emit-registers.py --check    # exit 1 if any generated artifact has drifted

Exit: 0 clean, 1 drift (--check) or a source error, 2 on a usage error.
"""
from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "references" / "registers"
STYLE_DIR = ROOT / "output-styles"
SKILL_FILE = ROOT / "skills" / "writing-register" / "SKILL.md"
# The plan's `Domain` -> the output style's `name:`, for scripts/set-output-style.ts. Generated for
# the same reason everything else here is: hand-writing `legal -> "Law review"` anywhere else is a
# fourth copy that goes stale the first time a style is renamed, and it fails SILENTLY — an
# unresolvable name just leaves the user on the default style with nothing reported.
MAP_FILE = SOURCE_DIR / "output-style-map.json"

# Order is load-bearing in the combined skill: general is the base layer the two domain registers
# sit on top of, so it is read first there as well.
STYLES = ("general", "legal", "econ")

SHARED_START = "<!-- SHARED-BASE:START -->"
SHARED_END = "<!-- SHARED-BASE:END -->"
STYLE_ONLY_START = "<!-- STYLE-ONLY:START -->"
STYLE_ONLY_END = "<!-- STYLE-ONLY:END -->"

GENERATED = (
    "<!-- GENERATED by scripts/emit-registers.py from references/registers/*.md.\n"
    "     DO NOT HAND-EDIT: `emit-registers.py --check` fails and the edit is lost on the next\n"
    "     regeneration. Edit the source in references/registers/ instead. -->"
)

SKILL_FRONTMATTER = """---
name: writing-register
description: Register and voice rules for law review, finance/accounting journal, and general professional prose — corpus-measured contrasts, filtered style-guide rules, and the shipped AI-tic prohibitions. Preloaded into the writing drafter and prose reviewer; use when drafting or grading prose in one of those three registers.
---"""

SKILL_PREAMBLE = """# Register and Voice

Three registers, measured against two control corpora — **5,560,816 sentences** of T14 flagship law
review scholarship and **8,733,332 sentences** of finance/accounting scholarship, 14,294,148
together.

**All three are here on purpose.** The register facts are contrastive by construction: every one of
them carries both columns (`we` is 0.87% of law sentences and 7.75% of finance sentences), and an
agent that sees both sides and is told which applies is better informed than one that sees half.
Your dispatch prompt names the draft's style — `legal`, `econ`, or `general`. Read that register's
section, read the shared base at the end, and read the other two only as contrast.

**Do not apply another register's rules.** The single most damaging thing you can do with this file
is import a rule across the line: stripping the authorial `we` from a finance paper, or adding
`We find that…` to a law review Part. The corpus separation is large and real, and a rule that is
correct in one register is a defect in the other."""


def die(msg: str, code: int = 1) -> None:
    print(f"emit-registers: {msg}", file=sys.stderr)
    sys.exit(code)


def parse_source(path: Path) -> tuple[dict[str, str], str]:
    """Split `---`-delimited frontmatter from the body. Deliberately NOT yaml.safe_load: the
    frontmatter is five flat `key: value` lines, and a hand parser keeps this script runnable by
    bare `python3` in a test harness that has no pyyaml."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        die(f"{path.name}: missing `---` frontmatter")
    end = text.find("\n---\n", 3)
    if end == -1:
        die(f"{path.name}: unterminated frontmatter")
    meta: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if not line.strip():
            continue
        key, sep, value = line.partition(":")
        if not sep:
            die(f"{path.name}: frontmatter line is not `key: value`: {line!r}")
        meta[key.strip()] = value.strip()
    for required in ("style", "slug", "name", "description", "keep-coding-instructions"):
        if required not in meta:
            die(f"{path.name}: frontmatter is missing `{required}`")
    return meta, text[end + 5:].strip("\n")


def _marker_lines(body: str, marker: str) -> list[int]:
    """Character offsets of every line that IS the marker, alone. Anchoring to a whole line rather
    than matching the substring anywhere means a source that *discusses* `SHARED-BASE:START` in
    prose or inside a fenced example cannot silently relocate the cut."""
    offsets, pos = [], 0
    for line in body.split("\n"):
        if line.strip() == marker:
            offsets.append(pos)
        pos += len(line) + 1
    return offsets


def cut_block(body: str, start: str, end: str, unique: bool = True) -> tuple[str, str]:
    """Return (body without the FIRST delimited block, that block's contents). Absent block -> (body
    unchanged, ''). A start without an end is an error rather than a silent truncation, and with
    `unique` a REPEATED marker is too: `.find`/`.replace` take only the first hit, so a second block
    survived into the output carrying its own stray markers while `--check` still passed."""
    starts, ends = _marker_lines(body, start), _marker_lines(body, end)
    if unique and (len(starts) > 1 or len(ends) > 1):
        die(f"{start}/{end} appears {max(len(starts), len(ends))} times; exactly one pair is allowed")
    if len(starts) != len(ends):
        die(f"{start} appears {len(starts)} time(s) but {end} appears {len(ends)} time(s)")
    if not starts:
        if ends:
            die(f"found {end} with no matching {start}")
        return body, ""
    if not ends:
        die(f"found {start} with no matching {end}")
    i, j = starts[0], ends[0]
    if j < i:
        die(f"{end} precedes {start}")
    inner = body[i + len(start):j].strip("\n")
    outer = (body[:i].rstrip("\n") + "\n\n" + body[j + len(end):].lstrip("\n")).strip("\n")
    return outer, inner


def render_style(meta: dict[str, str], body: str, shared: str) -> str:
    """One output style. `general` already contains the shared base inline (it IS the base layer);
    the two domain registers get it appended."""
    body = body.replace(STYLE_ONLY_START + "\n", "").replace(STYLE_ONLY_START, "")
    body = body.replace("\n" + STYLE_ONLY_END, "").replace(STYLE_ONLY_END, "")
    if meta["style"] != "general":
        body = body.rstrip("\n") + "\n\n" + shared
    body = body.replace("{{STYLE}}", meta["style"])
    return (
        "---\n"
        f"name: {meta['name']}\n"
        f"description: {meta['description']}\n"
        f"keep-coding-instructions: {meta['keep-coding-instructions']}\n"
        "---\n\n"
        f"{GENERATED}\n\n"
        f"{body.strip()}\n"
    )


def demote(body: str) -> str:
    """Push every heading down one level so a source's `##` nests under the combined skill's own
    register heading. Fenced code is not scanned for headings here because no source block contains
    a line that could be mistaken for one — a `#` in the audit snippet is a shell comment at column
    0 only if someone writes it that way, and `## ` requires the space."""
    out = []
    for line in body.split("\n"):
        stripped = line.lstrip("#")
        hashes = len(line) - len(stripped)
        out.append("#" + line if hashes >= 2 and stripped.startswith(" ") else line)
    return "\n".join(out)


HEADINGS = {
    "general": "## Register: general professional prose (comment letters, memos, briefs)",
    "legal": "## Register: law review",
    "econ": "## Register: finance / accounting journal",
}


def render_skill(sources: dict[str, tuple[dict[str, str], str]], shared: str) -> str:
    """The ONE combined preload artifact. Every register, contrastively, plus the shared base once.

    The per-register `keep-coding-instructions` note is cut here: it explains an output-style
    frontmatter field that does not exist in a skill, so carrying it over would be an instruction
    about a mechanism the reader is not using."""
    parts = [SKILL_FRONTMATTER, "", GENERATED, "", SKILL_PREAMBLE]
    for style in STYLES:
        _, body = sources[style]
        # STYLE-ONLY is repeatable — a source may carry several notes that make sense only in an
        # output style. SHARED-BASE is not; there is exactly one base layer.
        while _marker_lines(body, STYLE_ONLY_START):
            body, _cut = cut_block(body, STYLE_ONLY_START, STYLE_ONLY_END, unique=False)
        parts += ["", "---", "", HEADINGS[style], "", demote(body).strip()]
    shared_body = demote(shared).replace("{{STYLE}}", "<legal|econ|general>")
    parts += ["", "---", "", "## The shared base — applies to all three registers", "", shared_body.strip()]
    return "\n".join(parts).strip() + "\n"


def build() -> dict[Path, str]:
    sources: dict[str, tuple[dict[str, str], str]] = {}
    for style in STYLES:
        path = SOURCE_DIR / f"{style}.md"
        if not path.exists():
            die(f"missing source {path.relative_to(ROOT)}")
        meta, body = parse_source(path)
        if meta["style"] != style:
            die(f"{path.name}: frontmatter style={meta['style']!r} does not match the filename")
        sources[style] = (meta, body)

    general_body, shared = cut_block(sources["general"][1], SHARED_START, SHARED_END)
    if not shared:
        die("references/registers/general.md carries no SHARED-BASE block")
    # The general OUTPUT STYLE keeps the shared base inline where the author put it; only the
    # combined skill and the two domain styles need it lifted out.
    general_style_body = sources["general"][1].replace(SHARED_START + "\n", "").replace(
        "\n" + SHARED_END, ""
    )

    artifacts: dict[Path, str] = {}
    for style in STYLES:
        meta, body = sources[style]
        artifacts[STYLE_DIR / f"{meta['slug']}.md"] = render_style(
            meta, general_style_body if style == "general" else body, shared
        )
    artifacts[SKILL_FILE] = render_skill({**sources, "general": (sources["general"][0], general_body)}, shared)
    artifacts[MAP_FILE] = json.dumps(
        {
            "_generated": "scripts/emit-registers.py — do not hand-edit",
            "styles": {sources[s][0]["style"]: sources[s][0]["name"] for s in STYLES},
        },
        indent=2,
    ) + "\n"
    return artifacts


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate register output styles and the preload skill.")
    ap.add_argument("--check", action="store_true", help="exit 1 if any generated artifact has drifted")
    args = ap.parse_args()

    artifacts = build()

    if args.check:
        drifted = []
        # A STALE STYLE IS STILL LIVE. `output-styles/` is an auto-discovered plugin component
        # directory, so a generated file left behind after a source is renamed keeps appearing in
        # `/config` with nobody maintaining it. Checking only the expected paths reported OK while
        # that file sat there — an orphan is drift, not an unrelated file.
        expected = {p.name for p in artifacts if p.parent == STYLE_DIR}
        for stray in sorted(STYLE_DIR.glob("*.md")):
            if stray.name == "README.md" or stray.name in expected:
                continue
            drifted.append(stray)
            print(
                f"ORPHAN {stray.relative_to(ROOT)} — no source in references/registers/ produces it.\n"
                "  Delete it, or add the source back. It is auto-discovered and still shipping.",
                file=sys.stderr,
            )
        for path, want in artifacts.items():
            have = path.read_text(encoding="utf-8") if path.exists() else ""
            if have != want:
                drifted.append(path)
                rel = path.relative_to(ROOT)
                print(f"DRIFT  {rel}", file=sys.stderr)
                diff = difflib.unified_diff(
                    have.splitlines(), want.splitlines(),
                    fromfile=f"{rel} (on disk)", tofile=f"{rel} (from source)", lineterm="", n=1,
                )
                for line in list(diff)[:40]:
                    print("  " + line, file=sys.stderr)
        if drifted:
            print(
                f"\n{len(drifted)} generated file(s) disagree with references/registers/*.md.\n"
                "Run `python3 scripts/emit-registers.py` — and if you hand-edited a generated file, "
                "move the edit into the source first.",
                file=sys.stderr,
            )
            return 1
        print(f"OK  {len(artifacts)} generated file(s) match references/registers/*.md")
        return 0

    for path, want in artifacts.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        changed = not path.exists() or path.read_text(encoding="utf-8") != want
        path.write_text(want, encoding="utf-8")
        print(f"{'wrote ' if changed else 'same  '} {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
