#!/usr/bin/env bun
/**
 * Set `outputStyle` in a project's `.claude/settings.local.json` to the register its APPROVED
 * writing plan declares.
 *
 * IT DERIVES THE STYLE; IT DOES NOT TAKE ONE. The style is read from the authenticated
 * receipt-selected plan's `## Writing Intent` `Domain`, through the same
 * `authenticatedWritingPlan()` that `hooks/writing-prose-check.ts` uses to pick `--style`. Accepting
 * a style argument would create a second source for "what register is this," and a clarify answer
 * the user later revised during planning would silently outrank the plan. `.claude/CLAUDE.md`'s
 * rule is derive before you record; this is that rule in code rather than in prose.
 *
 * NO APPROVED PLAN MEANS NO WRITE. Not a default, not a guess. An unapproved episode has no
 * authenticated register, and picking one would be inventing authority.
 *
 * IT MERGES EXACTLY ONE KEY. `.claude/settings.local.json` carries `permissions` and whatever else
 * the user has put there, it OUTRANKS project settings, and Claude Code adds it to the global git
 * excludes when it writes there — so a clobber is both damaging and invisible to `git status`.
 * Malformed JSON is a REFUSAL, never an overwrite: a settings file that failed to parse is far more
 * likely to be mid-edit than to be garbage, and replacing it would destroy work.
 *
 * IT TAKES EFFECT NEXT SESSION. The output style is part of the system prompt, which Claude Code
 * reads once at session start, so this cannot change the session that runs it. That is why the
 * caller invokes it at the end of the approval/review episode: `writing-setup` already requires a
 * fresh session before implementation, so the boundary the setting needs is one the workflow was
 * taking anyway. Compare the retired plans-directory restart gate, which had to become a GATE because a
 * mid-session `plansDirectory` left the episode unauthenticated. This is prose voice, not
 * authentication — the drafting subagent's preloaded `writing-register` and the plugin-wide prose
 * audit both still apply — so a notice is proportionate where a gate would not be.
 *
 * Usage:
 *   bun scripts/set-output-style.ts <projectRoot>            # write it
 *   bun scripts/set-output-style.ts <projectRoot> --dry-run  # report what it would do
 *
 * Exit: 0 written or already correct, 1 refused (no approved plan, unknown style, unparseable
 * settings), 2 usage error.
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync, renameSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { authenticatedWritingPlan } from "../hooks/lib/writing-plan-context.ts";

const PLUGIN_ROOT = dirname(import.meta.dir);
const MAP_FILE = join(PLUGIN_ROOT, "references", "registers", "output-style-map.json");

export type Outcome =
  | { ok: true; changed: boolean; style: string; name: string; settingsPath: string }
  | { ok: false; reason: string };

/** style -> output style `name:`, generated by scripts/emit-registers.py from the register sources. */
export function styleMap(mapFile: string = MAP_FILE): Record<string, string> {
  try {
    const parsed = JSON.parse(readFileSync(mapFile, "utf8"));
    const styles = parsed?.styles;
    if (styles === null || typeof styles !== "object" || Array.isArray(styles)) return {};
    // ONLY NON-EMPTY STRINGS. A truthy non-string value (an object, a number) sails past a bare
    // `if (!name)` at the call site and gets written as `outputStyle` — a value no output style can
    // ever match, so the user silently keeps the default with nothing reported. Dropping it here
    // turns that into the "no output style for this Domain" refusal, which says so.
    const out: Record<string, string> = {};
    for (const [style, name] of Object.entries(styles)) {
      if (typeof name === "string" && name.trim() !== "") out[style] = name;
    }
    return out;
  } catch {
    return {};
  }
}

/**
 * Merge exactly `outputStyle` into a settings file, preserving every sibling key AND the file's
 * own key order — a wholesale rewrite of the user's settings would show up as a large diff in a
 * file they may well be reading by hand.
 */
export function mergeOutputStyle(settingsPath: string, name: string, dryRun = false): Outcome {
  let existing: Record<string, unknown> = {};
  if (existsSync(settingsPath)) {
    let raw: string;
    try {
      raw = readFileSync(settingsPath, "utf8");
    } catch (e) {
      return { ok: false, reason: `cannot read ${settingsPath}: ${(e as Error).message}` };
    }
    if (raw.trim() !== "") {
      try {
        const parsed = JSON.parse(raw);
        if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
          return { ok: false, reason: `${settingsPath} is not a JSON object — refusing to overwrite it` };
        }
        existing = parsed as Record<string, unknown>;
      } catch (e) {
        // REFUSE, DO NOT REPLACE. Far more likely mid-edit than garbage.
        return { ok: false, reason: `${settingsPath} is not valid JSON (${(e as Error).message}) — refusing to overwrite it` };
      }
    }
  }

  if (existing.outputStyle === name) {
    return { ok: true, changed: false, style: "", name, settingsPath };
  }
  if (!dryRun) {
    const merged = { ...existing, outputStyle: name };
    mkdirSync(dirname(settingsPath), { recursive: true });
    // ATOMIC: write a sibling, then rename. A direct write truncates first, so a crash or a full
    // disk between truncate and flush leaves the user with a settings file that is neither the old
    // one nor the new one — and this file carries `permissions`, outranks project settings, and is
    // git-excluded, so there is nothing to restore it from. `rename` within the same directory is
    // atomic on every platform this runs on.
    const tmp = `${settingsPath}.${process.pid}.tmp`;
    try {
      writeFileSync(tmp, JSON.stringify(merged, null, 2) + "\n", "utf8");
      renameSync(tmp, settingsPath);
    } catch (e) {
      try { rmSync(tmp, { force: true }); } catch { /* best effort */ }
      return { ok: false, reason: `could not write ${settingsPath}: ${(e as Error).message}` };
    }
  }
  return { ok: true, changed: true, style: "", name, settingsPath };
}

/** The whole operation: derive the register from the approved plan, then merge. */
export function setOutputStyle(projectRoot: string, dryRun = false, mapFile: string = MAP_FILE): Outcome {
  const root = resolve(projectRoot);
  const plan = authenticatedWritingPlan(root);
  if (!plan) {
    return { ok: false, reason: `no APPROVED receipt-selected writing plan at or above ${root} — nothing to derive a register from` };
  }
  const style = (plan.style || "").toLowerCase();
  const map = styleMap(mapFile);
  const name = map[style];
  if (!name) {
    const known = Object.keys(map).sort().join(", ") || "(the style map is missing or empty)";
    return { ok: false, reason: `the plan declares Domain "${plan.style || "(empty)"}", which has no output style. Known: ${known}` };
  }
  const result = mergeOutputStyle(join(plan.projectRoot, ".claude", "settings.local.json"), name, dryRun);
  return result.ok ? { ...result, style } : result;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const positional = args.filter((a) => !a.startsWith("--"));
  if (positional.length !== 1) {
    console.error("usage: set-output-style.ts <projectRoot> [--dry-run]");
    process.exit(2);
  }
  const result = setOutputStyle(positional[0], dryRun);
  if (!result.ok) {
    console.error(`set-output-style: ${result.reason}`);
    process.exit(1);
  }
  if (!result.changed) {
    console.log(`outputStyle is already "${result.name}" in ${result.settingsPath} — nothing to do.`);
    process.exit(0);
  }
  console.log(
    `${dryRun ? "WOULD SET" : "set"} outputStyle = "${result.name}"  (plan Domain: ${result.style})\n` +
      `  ${result.settingsPath}\n\n` +
      "TAKES EFFECT NEXT SESSION. The output style is part of the system prompt, which Claude Code\n" +
      "reads once at session start — this session keeps whatever style it started with. Drafting\n" +
      "happens in a fresh session anyway, so the next one picks it up.\n" +
      "It shapes the MAIN conversation only; the drafting and reviewing subagents get the same\n" +
      "register through the preloaded `writing-register` skill regardless.",
  );
}

if (import.meta.main) await main();
