#!/usr/bin/env bun
/**
 * Emit a plan-bound implementation workflow into the project's official, reviewable location.
 *
 * WHY A GENERATOR AND NOT A HAND-WRITTEN RUNNER
 *   `workflows/beat-implement.js` was one static script that tried to do plan-specific filesystem
 *   work at runtime. It could never run: the Workflow runtime forbids `import()`, `process` and
 *   `Buffer`, and gives the script "no direct filesystem or shell access ... Agents read, write, and
 *   run commands. The script coordinates the agents."
 *
 *   Generating the script dissolves that. Every plan-specific value — task ids, prompts, writable
 *   paths, the plan hash — is resolved HERE, in an ordinary script with full filesystem access, and
 *   baked into the emitted source as a literal. The emitted script is therefore pure control flow by
 *   construction rather than by discipline, and this module asserts that before it writes.
 *
 * WHERE IT GOES, AND WHY THERE
 *   `<project>/.claude/workflows/<name>.js` — the location Claude Code itself uses for saved
 *   workflows. It is committed with the repo, diffable in review, and runnable as `/<name>` in a
 *   later session. A generated orchestration that nobody can read is the same opacity problem as an
 *   agent that self-reports.
 *
 * SYMLINK REFUSAL, MIRRORING CLAUDE CODE
 *   The docs are explicit for the project location: Claude Code "refuses if `.claude`,
 *   `.claude/workflows`, or the target file is a symlink", because following the link could place
 *   the file outside the location you chose. That is the same escape this repo has been closing all
 *   week in `readArtifactSnapshot` and `captureWorktreePath`, so the same refusal is applied here
 *   rather than trusting the writer to be pointed somewhere safe.
 */
import { lstatSync, mkdirSync, realpathSync, writeFileSync } from "node:fs";
import { join, relative, isAbsolute } from "node:path";

export type EmitTask = {
  id: string;
  name: string;
  prompt: string;
  dependsOn?: readonly string[];
};

export type EmitRequest = {
  projectDir: string;
  /** The receipt-selected plan this orchestration implements. The script is bound to it. */
  planFile: string;
  planHash: string;
  /** Domain that supplied the structure — writing, workshop, ds, dev, work, workflow-creator. */
  domain: string;
  /** Phase titles the domain skill supplies; the tasks are distributed across them in order. */
  phases: readonly string[];
  tasks: readonly EmitTask[];
};

/** The runtime's prohibitions. Identical to tests/workflow-runtime-purity.test.mjs on purpose. */
const FORBIDDEN: readonly [string, RegExp][] = [
  ["import()", /\bimport\s*\(/],
  ["import.meta", /\bimport\s*\.\s*meta\b/],
  ["process.", /\bprocess\s*\./],
  ["Buffer", /\bBuffer\b/],
];

/**
 * Refuse to write through a symlinked `.claude`, `.claude/workflows`, or target file, and refuse a
 * destination that escapes the project. Returns the directory to write into.
 */
export function resolveWorkflowDir(projectDir: string, name: string): string {
  const root = realpathSync(projectDir);
  const claude = join(root, ".claude");
  const dir = join(claude, "workflows");
  for (const path of [claude, dir, join(dir, `${name}.js`)]) {
    try {
      if (lstatSync(path).isSymbolicLink()) {
        throw new Error(`refusing to write through a symlink at ${path}; a link here can place the generated workflow outside the project`);
      }
    } catch (error) {
      // ENOENT is the normal case for a path we are about to create; anything else is a real refusal.
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
  }
  mkdirSync(dir, { recursive: true });
  const real = realpathSync(dir);
  const rel = relative(root, real);
  if (!rel || rel.startsWith("..") || isAbsolute(rel)) {
    throw new Error(`refusing to write outside the project: ${real}`);
  }
  return real;
}

const literal = (value: unknown) => JSON.stringify(value ?? null);

export function renderWorkflow(request: EmitRequest): string {
  const { domain, planFile, planHash, phases, tasks } = request;
  const name = `${domain}-implement`;
  // Every value below is a literal resolved at generation time. The script computes nothing about
  // the filesystem, which is why it satisfies the runtime's constraints by construction.
  return `export const meta = {
  name: ${literal(name)},
  description: ${literal(`Implement the ${domain} plan ${planFile} (${planHash.slice(0, 12)}) — generated, do not hand-edit.`)},
  whenToUse: 'Regenerated by beat-implement from the receipt-selected plan. Bound to one plan hash; a new plan produces a new script.',
  phases: ${literal(phases.map(title => ({ title })))},
}

// GENERATED — do not hand-edit. Regenerate with scripts/beat/emit-implementation-workflow.ts.
//
// Bound to exactly one plan. If the plan changes, its hash changes and this script is replaced;
// editing it by hand detaches the orchestration from the approval that authorised it.
const PLAN_FILE = ${literal(planFile)}
const PLAN_HASH = ${literal(planHash)}
const TASKS = ${JSON.stringify(tasks.map(task => ({ id: task.id, name: task.name, prompt: task.prompt, dependsOn: task.dependsOn ?? [] })), null, 2)}

const RESULT = {
  type: 'object', additionalProperties: false,
  required: ['taskId', 'status', 'summary', 'changedFiles'],
  properties: {
    taskId: { type: 'string' },
    status: { type: 'string', enum: ['implemented', 'blocked', 'failed'] },
    summary: { type: 'string' },
    changedFiles: { type: 'array', items: { type: 'string' } },
  },
}

// Waves come from the plan's dependency graph, computed here over literals — no filesystem, no
// discovery. A task dispatches only once every task it depends on has returned.
const done = new Set()
const results = []
let remaining = TASKS.slice()
let waveIndex = 0
while (remaining.length) {
  const ready = remaining.filter(task => task.dependsOn.every(id => done.has(id)))
  if (!ready.length) throw new Error('generated plan has an unsatisfiable dependency; regenerate from the plan')
  phase(${literal(phases[0] ?? "Implement")})
  log(\`wave \${++waveIndex}: \${ready.length} task(s)\`)
  // SEQUENTIAL, NOT parallel(). The observation hooks bracket each dispatch with a git observation of
  // the WHOLE working tree, so a sibling task writing inside this task's pre/post window lands in this
  // task's delta and is reported against an agent that did nothing wrong. preflight.ts returns
  // executionMode: 'sequential' for exactly this reason — and this generator emitted parallel() anyway,
  // which made that returned value false for every generated script. Found by an independent review
  // after the identical defect had been fixed by hand in writing-draft.js and workshop-generate.js.
  const wave = []
  for (const task of ready) {
    wave.push(await agent(
      \`IMMUTABLE PLAN IDENTITY\\nPLAN_FILE: \${PLAN_FILE}\\nPLAN_HASH: \${PLAN_HASH}\\n\\n\${task.prompt}\\n\\nReturn RESULT.\`,
      { label: task.id, schema: RESULT },
    ))
  }
  for (const [index, raw] of wave.entries()) {
    const task = ready[index]
    // Evidence is bound to the task captured at DISPATCH, never to the id the agent reports back —
    // a swapped echo must not rebind one task's result onto another.
    const bound = raw && String(raw.taskId) === task.id ? raw : null
    results.push({ taskId: task.id, planHash: PLAN_HASH, status: bound ? bound.status : 'failed',
      summary: bound ? bound.summary : 'agent returned no result, or reported a different task id',
      changedFiles: bound ? bound.changedFiles : [] })
    done.add(task.id)
  }
  remaining = remaining.filter(task => !done.has(task.id))
}

const failed = results.filter(result => result.status !== 'implemented')
log(failed.length ? \`\${failed.length}/\${results.length} task(s) did not implement\` : \`all \${results.length} task(s) implemented\`)
return {
  planFile: PLAN_FILE,
  planHash: PLAN_HASH,
  overallPass: failed.length === 0,
  results,
  // The write guard runs in hooks around each dispatch, not here: a workflow script has no
  // filesystem access, so it cannot observe what an agent wrote. This value is the agents' own
  // account and is NOT evidence — the caller's verification step owns that.
  reportedOnly: true,
}
`;
}

/**
 * The domain becomes a FILENAME, so it must be a bare identifier.
 *
 * `join(dir, `${domain}-implement.js`)` with `domain = "../../evil"` resolves to
 * `<project>/evil-implement.js` — outside `.claude/workflows/` entirely, defeating the symlink and
 * containment checks in `resolveWorkflowDir`, which validate the DIRECTORY and never the joined
 * target. `preflight.ts` validates its own workflow identity, but this function and the stdin CLI are
 * exported and reachable without it.
 */
function assertBareIdentifier(domain: string): void {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(domain)) {
    throw new Error(`refusing to emit: domain must be a bare lowercase identifier, got ${JSON.stringify(domain)}. It becomes a filename, and a separator or traversal segment escapes the workflows directory.`);
  }
}

export function emitImplementationWorkflow(request: EmitRequest): { path: string; source: string } {
  assertBareIdentifier(request.domain);
  const source = renderWorkflow(request);
  for (const [construct, pattern] of FORBIDDEN) {
    // Strip comments before scanning, exactly as the purity suite does: the header legitimately
    // names these constructs while explaining why they are absent.
    const code = source.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");
    if (pattern.test(code)) {
      throw new Error(`generated workflow contains ${construct}, which the Workflow runtime rejects; the generator must resolve it instead of emitting it`);
    }
  }
  const name = `${request.domain}-implement`;
  const dir = resolveWorkflowDir(request.projectDir, name);
  const path = join(dir, `${name}.js`);
  writeFileSync(path, source);
  return { path, source };
}

if (import.meta.main) {
  const request = JSON.parse(await new Response(Bun.stdin.stream()).text()) as EmitRequest;
  const { path } = emitImplementationWorkflow(request);
  console.log(JSON.stringify({ ok: true, path }, null, 2));
}
