#!/usr/bin/env -S uv run python3
"""
dev-compile: deterministically compile a dev PLAN.md Implementation Order table into
a lean, project-specific Workflow script (.planning/run.js) from the shared template.

NO LLM. This replaces dev-implement.js's per-call LLM "discovery" agent. Parsing is via
the shared tolerant parser dev_plan_table.py (the same module the executable guard uses),
so compile and gate never disagree.

Unlike ds-compile, dev does NOT tier the implementer model (DESIGN D-dev-5): the
implementer inherits the session model (multi-step TDD needs capability); only the cheap
probe is pinned (haiku, in the template). dev also injects two prose sections the ds plan
lacks — Global Constraints (a 4th template hole) and per-task Task Interfaces.

Usage:
  dev_compile.py PLAN.md [--out RUN_JS] [--project DIR] [--template TPL]

Exit 0 on success; non-zero (with violations on stderr) if the plan is not compilable.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from dev_plan_table import parse_plan, toposort, Task  # noqa: E402

_HERE = Path(__file__).resolve()
_TEMPLATES = _HERE.parents[2] / "workflows" / "templates"
_DEFAULT_TEMPLATE = _TEMPLATES / "run-core.js"        # shared driver/helpers/schema (pass #9)
_DEFAULT_FRAGMENT = _TEMPLATES / "dev-task.js"         # dev D1/D2 bodies + recheckTrigger

# dev shares ONE working tree with no per-task worktree isolation (v1, DESIGN D-dev-1), so it is
# NOT isolation-safe: every level runs SEQUENTIALLY by construction (tree corruption is impossible).
# A future worktree mode flips this single flag without re-architecting the driver.
_ISOLATION_SAFE = False


def _level_modes(levels: list[list[str]]) -> list[str]:
    """Per-level intraLevel flag (S2, compiler-DERIVED). dev is not isolation-safe → all sequential."""
    return ["sequential" if not _ISOLATION_SAFE else "parallel" for _ in levels]


def _node_check(path: Path) -> bool:
    """`node --check` the emitted run.js — a splice has more failure modes than a single-file fill.
    Skips silently (returns True) if node is unavailable."""
    import shutil
    import subprocess
    node = shutil.which("node")
    if not node:
        return True
    proc = subprocess.run([node, "--check", str(path)], capture_output=True, text=True)
    if proc.returncode != 0:
        print(f"node --check FAILED on {path}:\n{proc.stderr}", file=sys.stderr)
    return proc.returncode == 0


def _spec_dict(t: Task) -> dict:
    return {
        "id": t.id, "name": t.name, "deps": t.deps, "files": t.files,
        "failingTest": t.failing_test, "verify": t.verify, "implements": t.implements,
        "done": t.done, "pauseAfter": t.pause_after, "interfaces": t.interfaces,
        "taskText": t.task_text,
    }


def _js_literal(value) -> str:
    """JSON is a subset of JS object/array literal syntax — safe to inject."""
    return json.dumps(value, ensure_ascii=False, indent=2)


def compile_plan(plan_path: Path, out_path: Path, project_dir: Path,
                 template_path: Path, fragment_path: Path) -> int:
    text = plan_path.read_text()
    res = parse_plan(text)
    if not res.ok:
        print("PLAN NOT COMPILABLE:\n- " + "\n- ".join(res.violations), file=sys.stderr)
        return 1

    specs = [_spec_dict(t) for t in res.tasks]
    levels = toposort(res.tasks)
    level_modes = _level_modes(levels)
    pauses = [s["id"] for s in specs if s["pauseAfter"]]

    meta = {
        "name": "dev-run",
        "description": (
            f"Compiled dev runner for {project_dir.name}: topo-runs {len(specs)} task(s) across "
            f"{len(levels)} dependency level(s) sequentially-within-level (shared tree), TDD "
            f"test-first, gating each on its Verify Command exit code (independent probe), pausing "
            f"at decisions/R4. Generated by dev-compile from PLAN.md — do not hand-edit; edit PLAN.md "
            f"and recompile."),
        "phases": [{"title": f"Level {i}", "detail": " ".join(levels[i])} for i in range(len(levels))]
                  + [{"title": "Gate", "detail": "independent probe of each Verify Command exit code"}],
    }

    template = template_path.read_text()
    fragment = fragment_path.read_text()

    # splice the per-domain fragment into __TASK_BODIES__ FIRST (exactly-once), so the data-hole
    # assertion below runs over the SPLICED result (catches a hole token leaking out of the fragment).
    body_hole = "/*__TASK_BODIES__*/"
    if template.count(body_hole) != 1:
        print(f"Template {template_path}: hole {body_hole} appears {template.count(body_hole)}× (expected 1).", file=sys.stderr)
        return 2
    template = template.replace(body_hole, fragment, 1)

    holes = {"/*__META__*/": _js_literal(meta),
             "/*__PROJECT__*/": json.dumps(str(project_dir)),
             "/*__TASKS__*/": _js_literal(specs),
             "/*__GLOBAL_CONSTRAINTS__*/": json.dumps(res.global_constraints),
             "/*__LEVEL_MODES__*/": _js_literal(level_modes)}
    for hole in holes:
        n = template.count(hole)
        if n != 1:
            print(f"After splice: hole {hole} appears {n}× (expected exactly 1). "
                  f"A hole token must not appear in documentation/comments.", file=sys.stderr)
            return 2

    banner = (
        "// GENERATED by dev-compile from PLAN.md — DO NOT EDIT. Edit PLAN.md and recompile.\n"
        f"// source: {plan_path}\n"
        f"// core: {template_path.name} + fragment: {fragment_path.name}\n"
        f"// tasks: {len(specs)} | levels: {len(levels)} | modes: {level_modes} | declared pauses: {pauses or 'none'}\n\n")
    out = banner + template
    for hole, repl in holes.items():
        out = out.replace(hole, repl, 1)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out)
    if not _node_check(out_path):
        return 3
    print(f"compiled {len(specs)} task(s), {len(levels)} level(s), modes={level_modes} → {out_path}")
    if pauses:
        print(f"  declared pause(s) at: {', '.join(pauses)}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("plan")
    ap.add_argument("--out")
    ap.add_argument("--project")
    ap.add_argument("--template", default=str(_DEFAULT_TEMPLATE))
    ap.add_argument("--fragment", default=str(_DEFAULT_FRAGMENT))
    a = ap.parse_args()

    plan_path = Path(a.plan).resolve()
    if not plan_path.is_file():
        print(f"PLAN.md not found: {plan_path}", file=sys.stderr)
        return 2
    out_path = Path(a.out).resolve() if a.out else plan_path.parent / "run.js"
    if a.project:
        project_dir = Path(a.project).resolve()
    else:
        p = plan_path.parent
        project_dir = p.parent if p.name == ".planning" else p
    return compile_plan(plan_path, out_path, project_dir,
                        Path(a.template).resolve(), Path(a.fragment).resolve())


if __name__ == "__main__":
    sys.exit(main())
