#!/usr/bin/env -S uv run python3
"""
dev-compile: deterministically compile a dev PLAN.md Implementation Order table into
a lean, project-specific Workflow script (.planning/run.js) from the shared template.

NO LLM. This replaces dev-implement.js's per-call LLM "discovery" agent. Parsing is via
the shared tolerant parser dev_plan_table.py (the same module the executable guard uses),
so compile and gate never disagree.

Unlike ds-compile, dev does NOT tier the implementer model (DESIGN D-dev-5): the
implementer inherits the session model (multi-step TDD needs capability); only the cheap
probe is pinned (haiku, in the template). dev also injects two prose sections the ds plan
lacks — Global Constraints (a 4th template hole) and per-task Task Interfaces.

The shared splice/hole-fill/node-check driver lives in scripts/lib/compile_core.py — this
file supplies only the dev-specific config (parser, spec-dict, level-modes, meta text).

Usage:
  dev_compile.py PLAN.md [--out RUN_JS] [--project DIR] [--template TPL]

Exit 0 on success; non-zero (with violations on stderr) if the plan is not compilable.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "lib"))
from dev_plan_table import parse_plan, toposort, Task  # noqa: E402
from compile_core import CompileConfig, main as _core_main  # noqa: E402

_HERE = Path(__file__).resolve()
_TEMPLATES = _HERE.parents[2] / "workflows" / "templates"

# dev shares ONE working tree with no per-task worktree isolation (v1, DESIGN D-dev-1), so it is
# NOT isolation-safe: every level runs SEQUENTIALLY by construction (tree corruption is impossible).
# A future worktree mode flips this single flag without re-architecting the driver.
_ISOLATION_SAFE = False


def _level_modes(levels: list[list[str]]) -> list[str]:
    """Per-level intraLevel flag (S2, compiler-DERIVED). dev is not isolation-safe → all sequential."""
    return ["sequential" if not _ISOLATION_SAFE else "parallel" for _ in levels]


def _spec_dict(t: Task) -> dict:
    return {
        "id": t.id, "name": t.name, "deps": t.deps, "files": t.files,
        "failingTest": t.failing_test, "verify": t.verify, "implements": t.implements,
        "done": t.done, "pauseAfter": t.pause_after, "interfaces": t.interfaces,
        "taskText": t.task_text,
    }


def _describe(n_tasks: int, n_levels: int, project_dir: Path) -> str:
    return (
        f"Compiled dev runner for {project_dir.name}: topo-runs {n_tasks} task(s) across "
        f"{n_levels} dependency level(s) sequentially-within-level (shared tree), TDD "
        f"test-first, gating each on its Verify Command exit code (independent probe), pausing "
        f"at decisions/R4. Generated by dev-compile from PLAN.md — do not hand-edit; edit PLAN.md "
        f"and recompile.")


def _global_constraints_hole(res) -> str:
    return json.dumps(res.global_constraints)


CONFIG = CompileConfig(
    domain="dev",
    default_fragment_name="dev-task.js",
    parse_plan=parse_plan,
    toposort=toposort,
    spec_dict=_spec_dict,
    level_modes=_level_modes,
    level_modes_needs_by_id=False,
    run_name="dev-run",
    describe=_describe,
    global_constraints_hole=_global_constraints_hole,
    # dev has no output-first self-report (TDD uses testWritten/verifyPassed instead) —
    # leave outputsProduced optional/advisory (ds sets this True; see ds_compile.py).
    require_outputs_produced=False,
)


def main() -> int:
    return _core_main(CONFIG, _TEMPLATES)


if __name__ == "__main__":
    sys.exit(main())
