#!/usr/bin/env bash
# Extract ONE task's self-contained brief from a dev PLAN.md into a file the
# implementer/reviewer reads in a single call — so the task text, the Global
# Constraints, and the task's Interfaces never have to stream through the
# controller's (most expensive) context.
#
# Mirrors superpowers v6 `task-brief`, adapted to THIS repo's layout: tasks live
# in the machine-executable "Implementation Order" TABLE (one row per task), with
# Global Constraints and per-task Interfaces as sibling sections (both optional —
# backward-compatible with constraint-free / interface-free plans).
#
# Usage: task-brief.sh PLAN_FILE TASK_NUMBER [OUTFILE]
# Default OUTFILE: .planning/handoff/task-<N>-brief.md (relative to CWD = project root)
set -euo pipefail

if [ $# -lt 2 ] || [ $# -gt 3 ]; then
  echo "usage: task-brief.sh PLAN_FILE TASK_NUMBER [OUTFILE]" >&2
  exit 2
fi

plan=$1
n=$2
[ -f "$plan" ] || { echo "no such plan file: $plan" >&2; exit 2; }
case "$n" in *[!0-9]*|'') echo "TASK_NUMBER must be an integer, got: $n" >&2; exit 2;; esac

if [ $# -eq 3 ]; then
  out=$3
else
  out=".planning/handoff/task-${n}-brief.md"
fi
hdir=$(dirname "$out")
mkdir -p "$hdir"
# Self-contained guardrail: keep handoff artifacts untracked so they never get
# swept into the very review diff the reviewers read (recursive noise).
case "$hdir" in */handoff) [ -f "$hdir/.gitignore" ] || printf '*\n' > "$hdir/.gitignore" ;; esac

# 1. Global Constraints block (optional): from '## Global Constraints' to next '## '.
gc=$(awk '
  /^##[[:space:]]+Global Constraints/ { grab=1; next }
  grab && /^##[[:space:]]/ { grab=0 }
  grab { print }
' "$plan")

# 2. The Implementation Order table header + the task row.
hdr=$(awk '
  /^\|[[:space:]]*Task[[:space:]]*\|[[:space:]]*Deps/ { print; if ((getline nxt) > 0) print nxt; exit }
' "$plan")
row=$(awk -v n="$n" '
  $0 ~ ("^\\|[[:space:]]*" n "\\.") { print; exit }
' "$plan")
[ -n "$row" ] || { echo "task ${n} not found in ${plan} (no Implementation Order row '| ${n}. ...')" >&2; exit 3; }

# 3. The task's Interfaces sub-block (optional): '### Task N' to the next heading.
iface=$(awk -v n="$n" '
  $0 ~ ("^#+[[:space:]]+Task[[:space:]]+" n "([^0-9]|$)") { grab=1; print; next }
  grab && /^#+[[:space:]]/ { grab=0 }
  grab { print }
' "$plan")

{
  echo "# Task ${n} brief"
  echo
  echo "_Self-contained: read this file instead of the full PLAN.md. Generated by task-brief.sh._"
  echo
  echo "## Global Constraints (bind every task — obey verbatim)"
  if [ -n "$gc" ]; then printf '%s\n' "$gc"; else echo "_None declared in this plan._"; fi
  echo
  echo "## Task ${n} (Implementation Order row)"
  echo
  if [ -n "$hdr" ]; then printf '%s\n' "$hdr"; fi
  printf '%s\n' "$row"
  echo
  echo "## Task ${n} interfaces (consumes / produces)"
  if [ -n "$iface" ]; then printf '%s\n' "$iface"; else echo "_None declared in this plan._"; fi
} > "$out"

echo "wrote ${out}: $(wc -l < "$out" | tr -d ' ') lines (global-constraints: $([ -n "$gc" ] && echo yes || echo none), interfaces: $([ -n "$iface" ] && echo yes || echo none))"
